-- A resmon corpus at schema 13, written by resmon v2.1.0's own code.
--
-- Source: tag v2.1.0, commit a5ad6c60d3daeb4d5b4f324c16f1a84129c1969b
-- Generated by: fixtures/v2.1.0/generate_corpus.py (committed beside this file)
-- Regenerate:   python generate_corpus.py --source-tree <v2.1.0 checkout>
-- Verify:       python generate_corpus.py --source-tree <v2.1.0 checkout> --check
--
-- v2.2.0 is the first release that upgrades a real user across five schema
-- steps in one launch (13 -> 18). Every step has its own test, each starting
-- from the step before it; none of them starts from a database a *released*
-- resmon wrote. `test_cumulative_upgrade.py` executes this file and then calls
-- today's `init_db` once, the way a user's first launch after updating does.
--
-- Everything here is synthetic. No row is read from, copied from or derived
-- from any real corpus.
--
-- What is deliberately not in this file:
--   * the fts5 shadow tables (`documents_fts_{config,content,data,docsize,idx}`)
--     and `sqlite_sequence`'s CREATE -- SQLite makes both for itself. The
--     three `documents_fts_insert/_delete/_update` triggers ARE resmon's and
--     are here; they are what repopulates the search index when the documents
--     below are inserted.
--   * live timestamps. About twenty columns default to `datetime('now')`, so
--     the generator rewrites them from each row's rowid and then fails if any
--     value from the run's own clock survives. That is the one documented
--     normalisation between a regeneration and this file.

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

CREATE TABLE documents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_repository TEXT NOT NULL,
    external_id TEXT NOT NULL,
    doi TEXT,
    title TEXT NOT NULL,
    authors TEXT,
    abstract TEXT,
    publication_date TEXT,
    url TEXT,
    categories TEXT,
    metadata_hash TEXT NOT NULL,
    first_seen_at TEXT NOT NULL DEFAULT (datetime('now')),
    pub_sort TEXT GENERATED ALWAYS AS (COALESCE(publication_date, '')) VIRTUAL,
    UNIQUE(source_repository, external_id)
);
CREATE TABLE executions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    execution_type TEXT NOT NULL CHECK(execution_type IN ('deep_dive', 'deep_sweep', 'automated_sweep')),
    routine_id INTEGER,
    saved_configuration_id INTEGER,
    parameters TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT,
    status TEXT NOT NULL DEFAULT 'running' CHECK(status IN ('running', 'completed', 'failed', 'cancelled')),
    result_count INTEGER DEFAULT 0,
    new_result_count INTEGER DEFAULT 0,
    log_path TEXT,
    result_path TEXT,
    error_message TEXT,
    progress_events TEXT,
    current_stage TEXT, cancel_reason TEXT, dedup_total INTEGER, dedup_new INTEGER, dedup_duplicates INTEGER, dedup_invalid INTEGER, dedup_cross_source INTEGER,
    FOREIGN KEY (routine_id) REFERENCES routines(id) ON DELETE SET NULL,
    FOREIGN KEY (saved_configuration_id) REFERENCES saved_configurations(id) ON DELETE SET NULL
);
CREATE TABLE execution_documents (
    execution_id INTEGER NOT NULL,
    document_id INTEGER NOT NULL,
    is_new INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (execution_id, document_id),
    FOREIGN KEY (execution_id) REFERENCES executions(id) ON DELETE CASCADE,
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE TABLE routines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    schedule_cron TEXT NOT NULL,
    parameters TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    email_enabled INTEGER NOT NULL DEFAULT 0,
    email_ai_summary_enabled INTEGER NOT NULL DEFAULT 0,
    ai_enabled INTEGER NOT NULL DEFAULT 0,
    notify_on_complete INTEGER NOT NULL DEFAULT 0,
    ai_settings TEXT,
    storage_settings TEXT,
    -- Free text: what this routine is actually looking for, in the user's own
    -- words. The keyword string is what resmon *sends*; this is what the user
    -- *means*, and the coverage audit needs the second to judge the first. It
    -- is optional and defaults to nothing rather than to the keyword string,
    -- because "the user wrote this" and "we reused the query" are different
    -- facts and the audit says which one it is working from.
    intent TEXT,
    execution_location TEXT NOT NULL DEFAULT 'local'
        CHECK (execution_location IN ('local', 'cloud')),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_executed_at TEXT
);
CREATE TABLE saved_configurations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    config_type TEXT NOT NULL CHECK(config_type IN ('manual_dive', 'manual_sweep', 'routine')),
    parameters TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE cloud_sync (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    provider TEXT NOT NULL DEFAULT 'google_drive',
    account_info TEXT,
    is_linked INTEGER NOT NULL DEFAULT 0,
    auto_backup_enabled INTEGER NOT NULL DEFAULT 0,
    last_sync_at TEXT,
    sync_status TEXT DEFAULT 'idle' CHECK(sync_status IN ('idle', 'syncing', 'error'))
);
CREATE TABLE app_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
CREATE TABLE document_authors (
    document_id       INTEGER NOT NULL,
    author            TEXT NOT NULL,
    -- Schema 13 (2.1). All three are nullable and are NULL far more often than
    -- not: measured on 2026-09-06, OpenAlex carried an ORCID on 9 of 17
    -- authorships and Crossref on 2 of 84. NULL means **the source did not
    -- say**, never "this person has no ORCID", and nothing downstream may read
    -- it the second way.
    orcid             TEXT,
    affiliation       TEXT,
    -- The source's own author id, prefixed with its slug so two sources' ids
    -- can never be compared by accident: `semantic_scholar:1751762`.
    source_author_id  TEXT,
    PRIMARY KEY (document_id, author),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_document_authors_orcid
    ON document_authors(orcid) WHERE orcid IS NOT NULL;
CREATE INDEX idx_document_authors_author
    ON document_authors(author);
CREATE TABLE watch_profiles (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    kind          TEXT NOT NULL CHECK (kind IN ('person', 'institution', 'group')),
    display_name  TEXT NOT NULL,
    -- The canonical name plus aliases, as JSON: [{"value": ..., "script": ...}].
    names         TEXT NOT NULL DEFAULT '[]',
    -- {"orcid": {"value": ..., "cited": ...}, "openalex": {...}, ...}. Every
    -- identifier carries where the user got it, because an identifier nobody
    -- can trace is an assertion.
    identifiers   TEXT NOT NULL DEFAULT '{}',
    orcid         TEXT,
    affiliations  TEXT NOT NULL DEFAULT '[]',
    -- Keywords used **only** to disambiguate, never to search: a profile is a
    -- person, and narrowing their papers by topic would silently hide their work.
    field_hints   TEXT NOT NULL DEFAULT '[]',
    notes         TEXT,
    created_at    TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_watch_profiles_orcid
    ON watch_profiles(orcid) WHERE orcid IS NOT NULL;
CREATE TABLE watch_profile_members (
    profile_id        INTEGER NOT NULL,
    member_profile_id INTEGER NOT NULL,
    PRIMARY KEY (profile_id, member_profile_id),
    FOREIGN KEY (profile_id) REFERENCES watch_profiles(id) ON DELETE CASCADE,
    FOREIGN KEY (member_profile_id) REFERENCES watch_profiles(id) ON DELETE CASCADE
);
CREATE TABLE watch_profile_matches (
    document_id     INTEGER NOT NULL,
    profile_id      INTEGER NOT NULL,
    basis           TEXT NOT NULL
                    CHECK (basis IN ('identifier', 'name+affiliation', 'name_only')),
    matched_author  TEXT NOT NULL,
    evidence        TEXT,
    first_seen_at   TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (document_id, profile_id),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    FOREIGN KEY (profile_id) REFERENCES watch_profiles(id) ON DELETE CASCADE
);
CREATE INDEX idx_watch_profile_matches_profile
    ON watch_profile_matches(profile_id, first_seen_at DESC);
CREATE TABLE document_categories (
    document_id INTEGER NOT NULL,
    category    TEXT NOT NULL,
    PRIMARY KEY (document_id, category),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_document_categories_category
    ON document_categories(category);
CREATE INDEX idx_documents_source
    ON documents(source_repository);
CREATE INDEX idx_documents_first_seen
    ON documents(first_seen_at);
CREATE TABLE execution_sources (
    execution_id    INTEGER NOT NULL,
    source          TEXT NOT NULL,
    status          TEXT NOT NULL
        CHECK (status IN ('ok', 'error', 'skipped_missing_key', 'cancelled')),
    result_count    INTEGER NOT NULL DEFAULT 0,
    error_message   TEXT,
    credential_name TEXT,
    zero_reason     TEXT,
    zero_detail     TEXT,
    recorded_at     TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (execution_id, source),
    FOREIGN KEY (execution_id) REFERENCES executions(id) ON DELETE CASCADE
);
CREATE INDEX idx_execution_sources_source
    ON execution_sources(source);
CREATE TABLE execution_ai (
    execution_id    INTEGER NOT NULL,
    lane_index      INTEGER NOT NULL,
    lane_label      TEXT NOT NULL,
    lane_kind       TEXT NOT NULL
        CHECK (lane_kind IN ('subscription', 'api_key', 'local')),
    provider        TEXT NOT NULL,
    model           TEXT,
    credential_alias TEXT,
    outcome         TEXT NOT NULL
        CHECK (outcome IN ('running', 'ok', 'partial', 'failed', 'skipped')),
    error_kind      TEXT,
    http_status     INTEGER,
    safe_message    TEXT,
    docs_attempted  INTEGER NOT NULL DEFAULT 0,
    docs_succeeded  INTEGER NOT NULL DEFAULT 0,
    started_at      TEXT NOT NULL DEFAULT (datetime('now')),
    ended_at        TEXT,
    PRIMARY KEY (execution_id, lane_index),
    FOREIGN KEY (execution_id) REFERENCES executions(id) ON DELETE CASCADE
);
CREATE INDEX idx_execution_ai_exec
    ON execution_ai(execution_id);
CREATE TABLE watchdog_mutes (
    finding_key TEXT PRIMARY KEY,
    muted_at    TEXT NOT NULL DEFAULT (datetime('now')),
    note        TEXT
);
CREATE TABLE document_lifecycle (
    document_id     INTEGER NOT NULL,
    kind            TEXT NOT NULL,
    severity        TEXT NOT NULL
        CHECK (severity IN ('critical', 'caution', 'informational')),
    notice_key      TEXT NOT NULL,
    label           TEXT,
    notice_doi      TEXT,
    notice_url      TEXT NOT NULL,
    notice_date     TEXT,
    detail          TEXT,
    provider        TEXT NOT NULL,
    provider_source TEXT,
    first_seen_at   TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (document_id, kind, notice_key),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_document_lifecycle_severity
    ON document_lifecycle(severity);
CREATE TABLE document_lifecycle_checks (
    document_id   INTEGER PRIMARY KEY,
    checked_at    TEXT NOT NULL DEFAULT (datetime('now')),
    status        TEXT NOT NULL
        CHECK (status IN ('ok', 'no_identifier', 'error')),
    error_message TEXT,
    providers     TEXT,
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE TABLE document_embeddings (
    document_id INTEGER NOT NULL,
    model       TEXT NOT NULL,
    dims        INTEGER NOT NULL,
    vector      BLOB NOT NULL,
    fields      TEXT NOT NULL,
    embedded_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (document_id, model),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_document_embeddings_model
    ON document_embeddings(model);
CREATE TABLE document_links (
    document_a  INTEGER NOT NULL,
    document_b  INTEGER NOT NULL,
    kind        TEXT NOT NULL,
    score       REAL,
    method      TEXT NOT NULL,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (document_a, document_b, kind),
    CHECK (document_a < document_b),
    FOREIGN KEY (document_a) REFERENCES documents(id) ON DELETE CASCADE,
    FOREIGN KEY (document_b) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_document_links_b
    ON document_links(document_b);
CREATE TABLE assistant_sessions (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    runtime         TEXT NOT NULL,
    cli_session_id  TEXT,
    model           TEXT,
    title           TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE assistant_messages (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id      INTEGER NOT NULL,
    role            TEXT NOT NULL
        CHECK (role IN ('user', 'assistant', 'system')),
    content         TEXT NOT NULL DEFAULT '',
    tool_calls      TEXT,
    tool_results    TEXT,
    input_tokens    INTEGER,
    output_tokens   INTEGER,
    cost_usd        REAL,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (session_id) REFERENCES assistant_sessions(id) ON DELETE CASCADE
);
CREATE INDEX idx_assistant_messages_session
    ON assistant_messages(session_id, id);
CREATE INDEX idx_documents_pubsort ON documents(pub_sort DESC, id DESC);
CREATE VIRTUAL TABLE documents_fts USING fts5(
                title, abstract, authors,
                content='documents',
                content_rowid='id',
                tokenize='unicode61 remove_diacritics 2'
            );
CREATE TRIGGER documents_fts_insert AFTER INSERT ON documents BEGIN
            INSERT INTO documents_fts(rowid, title, abstract, authors)
            VALUES (new.id, new.title, new.abstract, new.authors);
        END;
CREATE TRIGGER documents_fts_delete AFTER DELETE ON documents BEGIN
            INSERT INTO documents_fts(documents_fts, rowid, title, abstract, authors)
            VALUES ('delete', old.id, old.title, old.abstract, old.authors);
        END;
CREATE TRIGGER documents_fts_update AFTER UPDATE ON documents BEGIN
            INSERT INTO documents_fts(documents_fts, rowid, title, abstract, authors)
            VALUES ('delete', old.id, old.title, old.abstract, old.authors);
            INSERT INTO documents_fts(rowid, title, abstract, authors)
            VALUES (new.id, new.title, new.abstract, new.authors);
        END;

-- documents: 12 row(s)
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (1, 'arxiv', '2401.00001', '10.48550/arXiv.2401.00001', 'Diffusion models for turbulent flow reconstruction', 'Ada Lovelace, Alan Turing, Grace Hopper', 'A study of diffusion models applied to turbulence.', '2026-01-15', 'https://example.org/arxiv/2401.00001', 'cs.LG, physics.flu-dyn', 'hash-arxiv-0001', '2026-02-01 05:37:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (2, 'openalex', 'W4391000001', '10.48550/arXiv.2401.00001', 'Diffusion models for turbulent flow reconstruction', 'Ada Lovelace, Alan Turing, Grace Hopper', 'A study of diffusion models applied to turbulence.', '2026-01-15', 'https://example.org/openalex/W4391000001', 'cs.LG', 'hash-arxiv-0001', '2026-02-01 06:14:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (3, 'pubmed', '39000001', '10.1000/pubmed.39000001', 'タンパク質折りたたみの速度論', '山田 太郎, Ana María Ñúñez-Olivér, Дмитрий Иванов', '折りたたみ速度の測定。', '2025-11-02', 'https://example.org/pubmed/39000001', 'q-bio.BM', 'hash-pubmed-0001', '2026-02-01 06:51:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (4, 'crossref', '10.1000/xyz123', '10.1000/xyz123', 'Ångström-scale imaging of catalytic surfaces', 'José González, Björn Östergaard', NULL, '2024-06-30', 'https://example.org/doi/10.1000/xyz123', 'cond-mat.mtrl-sci', 'hash-crossref-0001', '2026-02-01 07:28:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (5, 'zenodo', '10012345', NULL, 'Dataset: soil moisture readings, uncurated', NULL, NULL, NULL, NULL, NULL, 'hash-zenodo-0001', '2026-02-01 08:05:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (6, 'doaj', 'article-0001', '10.1000/doaj.0001', 'Open access publishing in the global south', 'Chimamanda Okeke, Ngũgĩ wa Thiong''o', 'A survey of open access mandates.', '2023-03-14', 'https://example.org/doaj/article-0001', 'soc', 'hash-doaj-0001', '2026-02-01 08:42:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (7, 'europepmc', 'PMC9000001', NULL, 'Retraction-prone preprints: a cohort study', 'Grace Hopper', 'A cohort study of preprints later retracted.', '2022-08-01', 'https://example.org/europepmc/PMC9000001', 'q-bio.OT, stat.AP', 'hash-europepmc-0001', '2026-02-01 09:19:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (8, 'semantic_scholar', 'corpusid:1751762', '10.1000/s2.1751762', 'Attention over sparse graphs', 'Ada Lovelace', 'Sparse attention for graph learning.', '2026-02-20', 'https://example.org/s2/1751762', 'cs.LG', 'hash-s2-0001', '2026-02-01 09:56:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (9, 'biorxiv', '2025.04.01.000001', '10.1101/2025.04.01.000001', 'A quote in the title: "folding" revisited, and a semicolon; too', 'O''Neill, Seán; D''Arcy, Máire', 'Punctuation that a naive SQL literal would break.', '2025-04-01', 'https://example.org/biorxiv/2025.04.01.000001', 'q-bio.BM', 'hash-biorxiv-0001', '2026-02-01 10:33:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (10, 'inspire_hep', '2700001', NULL, 'Constraints on axion-like particles', 'Lise Meitner, Chien-Shiung Wu', NULL, '2021-12-25', 'https://example.org/inspire/2700001', 'hep-ex', 'hash-inspire-0001', '2026-02-01 11:10:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (11, 'dryad', 'doi:10.5061/dryad.0001', '10.5061/dryad.0001', 'Supporting data for: axion constraints', 'Lise Meitner', 'Raw counts.', NULL, 'https://example.org/dryad/0001', NULL, 'hash-dryad-0001', '2026-02-01 11:47:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (12, 'osf', 'preprint-0001', NULL, 'Preregistration and the replication rate', 'Barbara McClintock, 山田 花子', 'Preregistered studies replicate more often.', '2020-05-05', 'https://example.org/osf/preprint-0001', 'psy, stat.AP', 'hash-osf-0001', '2026-02-01 12:24:00');

-- executions: 5 row(s)
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source") VALUES (1, 'deep_dive', 1, 1, '{"keywords": "diffusion", "index": 0}', '2026-02-01T06:00:00', '2026-02-01T06:12:00', 'completed', 12, 3, '/does/not/exist/run-0.log', '/does/not/exist/run-0.json', NULL, '[{"stage": "search", "source": "arxiv", "count": 9}, {"stage": "search", "source": "openalex", "count": 3}, {"stage": "dedup", "removed": 1}]', NULL, NULL, 12, 9, 2, 1, 1);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source") VALUES (2, 'deep_sweep', NULL, 2, '{"keywords": "diffusion", "index": 1}', '2026-02-02T06:00:00', '2026-02-02T06:12:00', 'failed', 13, 4, '/does/not/exist/run-1.log', '/does/not/exist/run-1.json', 'Upstream returned HTTP 503', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source") VALUES (3, 'automated_sweep', 2, NULL, '{"keywords": "diffusion", "index": 2}', '2026-02-03T06:00:00', '2026-02-03T06:12:00', 'completed', 14, 5, '/does/not/exist/run-2.log', '/does/not/exist/run-2.json', NULL, NULL, NULL, NULL, 7, 7, 0, 0, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source") VALUES (4, 'deep_dive', NULL, NULL, '{"keywords": "diffusion", "index": 3}', '2026-02-04T06:00:00', '2026-02-04T06:12:00', 'cancelled', 15, 6, '/does/not/exist/run-3.log', '/does/not/exist/run-3.json', NULL, NULL, NULL, 'user cancelled from the Dashboard', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source") VALUES (5, 'deep_sweep', NULL, NULL, '{"keywords": "diffusion", "index": 4}', '2026-02-05T06:00:00', NULL, 'running', 0, 0, NULL, NULL, NULL, NULL, 'querying sources', NULL, NULL, NULL, NULL, NULL, NULL);

-- execution_documents: 4 row(s)
INSERT INTO "execution_documents" ("execution_id", "document_id", "is_new") VALUES (1, 1, 1);
INSERT INTO "execution_documents" ("execution_id", "document_id", "is_new") VALUES (1, 2, 0);
INSERT INTO "execution_documents" ("execution_id", "document_id", "is_new") VALUES (1, 8, 1);
INSERT INTO "execution_documents" ("execution_id", "document_id", "is_new") VALUES (3, 7, 1);

-- routines: 3 row(s)
INSERT INTO "routines" ("id", "name", "schedule_cron", "parameters", "is_active", "email_enabled", "email_ai_summary_enabled", "ai_enabled", "notify_on_complete", "ai_settings", "storage_settings", "intent", "execution_location", "created_at", "updated_at", "last_executed_at") VALUES (1, 'Turbulence watch', '0 7 * * 1', '{"keywords": "diffusion turbulence", "sources": ["arxiv", "openalex"]}', 1, 0, 0, 1, 1, '{"lanes": ["subscription"]}', NULL, 'Anything new on learned turbulence closures.', 'local', '2026-02-01 05:37:00', '2026-02-01 05:37:00', NULL);
INSERT INTO "routines" ("id", "name", "schedule_cron", "parameters", "is_active", "email_enabled", "email_ai_summary_enabled", "ai_enabled", "notify_on_complete", "ai_settings", "storage_settings", "intent", "execution_location", "created_at", "updated_at", "last_executed_at") VALUES (2, 'Retraction watch', '0 8 * * *', '{"keywords": "retraction", "sources": ["europepmc"]}', 1, 0, 0, 1, 1, '{"lanes": ["subscription"]}', NULL, NULL, 'local', '2026-02-01 06:14:00', '2026-02-01 06:14:00', NULL);
INSERT INTO "routines" ("id", "name", "schedule_cron", "parameters", "is_active", "email_enabled", "email_ai_summary_enabled", "ai_enabled", "notify_on_complete", "ai_settings", "storage_settings", "intent", "execution_location", "created_at", "updated_at", "last_executed_at") VALUES (4, 'Legacy cloud routine', '0 4 * * 0', '{"keywords": "legacy", "sources": []}', 0, 0, 0, 0, 0, NULL, NULL, 'Left over from 2.0; resmon no longer runs this.', 'cloud', '2026-02-01 07:28:00', '2026-02-01 07:28:00', NULL);

-- saved_configurations: 3 row(s)
INSERT INTO "saved_configurations" ("id", "name", "config_type", "parameters", "created_at", "updated_at") VALUES (1, 'Weekly turbulence dive', 'manual_dive', '{"keywords": "diffusion turbulence", "sources": ["arxiv"]}', '2026-02-01 05:37:00', '2026-02-01 05:37:00');
INSERT INTO "saved_configurations" ("id", "name", "config_type", "parameters", "created_at", "updated_at") VALUES (2, 'Broad sweep', 'manual_sweep', '{"keywords": "protein folding", "sources": ["pubmed", "europepmc"]}', '2026-02-01 06:14:00', '2026-02-01 06:14:00');
INSERT INTO "saved_configurations" ("id", "name", "config_type", "parameters", "created_at", "updated_at") VALUES (3, 'Nightly routine config', 'routine', '{"keywords": "axion", "sources": ["inspire_hep"]}', '2026-02-01 06:51:00', '2026-02-01 06:51:00');

-- cloud_sync: 3 row(s)
INSERT INTO "cloud_sync" ("id", "provider", "account_info", "is_linked", "auto_backup_enabled", "last_sync_at", "sync_status") VALUES (1, 'google_drive', '{"email": "someone@example.org"}', 1, 1, '2026-02-01T05:00:00', 'idle');
INSERT INTO "cloud_sync" ("id", "provider", "account_info", "is_linked", "auto_backup_enabled", "last_sync_at", "sync_status") VALUES (2, 'google_drive', NULL, 0, 0, NULL, 'syncing');
INSERT INTO "cloud_sync" ("id", "provider", "account_info", "is_linked", "auto_backup_enabled", "last_sync_at", "sync_status") VALUES (3, 'google_drive', NULL, 0, 0, NULL, 'error');

-- app_settings: 9 row(s)
INSERT INTO "app_settings" ("key", "value") VALUES ('execution_sources_backfilled', '1');
INSERT INTO "app_settings" ("key", "value") VALUES ('dedup_columns_backfilled', '1');
INSERT INTO "app_settings" ("key", "value") VALUES ('schema_version', '13');
INSERT INTO "app_settings" ("key", "value") VALUES ('email_enabled', '0');
INSERT INTO "app_settings" ("key", "value") VALUES ('email_address', 'someone@example.org');
INSERT INTO "app_settings" ("key", "value") VALUES ('ai_provider', 'anthropic');
INSERT INTO "app_settings" ("key", "value") VALUES ('default_max_results', '50');
INSERT INTO "app_settings" ("key", "value") VALUES ('theme', 'dark');
INSERT INTO "app_settings" ("key", "value") VALUES ('export_footer', 'Compiled by resmon.
Don''t edit by hand.');

-- document_authors: 23 row(s)
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (1, 'Ada Lovelace', '0000-0002-1825-0097', 'Analytical Engine Group, London', 'arxiv:1');
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (1, 'Alan Turing', NULL, 'National Physical Laboratory', NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (1, 'Grace Hopper', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (2, 'Ada Lovelace', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (2, 'Alan Turing', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (2, 'Grace Hopper', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (3, '山田 太郎', '0000-0001-5109-3700', '東京大学, 理学部', 'pubmed:11');
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (3, 'Ana María Ñúñez-Olivér', NULL, 'Universidad de Chile', 'pubmed:12');
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (3, 'Дмитрий Иванов', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (4, 'José González', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (4, 'Björn Östergaard', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (6, 'Chimamanda Okeke', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (6, 'Ngũgĩ wa Thiong''o', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (7, 'Grace Hopper', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (8, 'Ada Lovelace', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (9, 'O''Neill', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (9, 'Seán; D''Arcy', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (9, 'Máire', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (10, 'Lise Meitner', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (10, 'Chien-Shiung Wu', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (11, 'Lise Meitner', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (12, 'Barbara McClintock', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (12, '山田 花子', NULL, NULL, NULL);

-- watch_profiles: 4 row(s)
INSERT INTO "watch_profiles" ("id", "kind", "display_name", "names", "identifiers", "orcid", "affiliations", "field_hints", "notes", "created_at", "updated_at") VALUES (1, 'person', 'Ada Lovelace', '[{"value": "Ada Lovelace", "script": "Latin"}, {"value": "A. Lovelace", "script": "Latin"}]', '{"orcid": {"value": "0000-0002-1825-0097", "cited": "https://example.org/orcid-page"}}', '0000-0002-1825-0097', '["Analytical Engine Group"]', '["machine learning"]', 'Watched since the corpus was started.', '2026-02-01 05:37:00', '2026-02-01 05:37:00');
INSERT INTO "watch_profiles" ("id", "kind", "display_name", "names", "identifiers", "orcid", "affiliations", "field_hints", "notes", "created_at", "updated_at") VALUES (2, 'person', '山田 太郎', '[{"value": "山田 太郎", "script": "Han"}, {"value": "Taro Yamada", "script": "Latin"}]', '{}', NULL, '["東京大学"]', '[]', NULL, '2026-02-01 06:14:00', '2026-02-01 06:14:00');
INSERT INTO "watch_profiles" ("id", "kind", "display_name", "names", "identifiers", "orcid", "affiliations", "field_hints", "notes", "created_at", "updated_at") VALUES (3, 'institution', 'National Physical Laboratory', '[{"value": "National Physical Laboratory", "script": "Latin"}]', '{"ror": {"value": "02mhbdp94", "cited": "https://example.org/ror-page"}}', NULL, '[]', '[]', NULL, '2026-02-01 06:51:00', '2026-02-01 06:51:00');
INSERT INTO "watch_profiles" ("id", "kind", "display_name", "names", "identifiers", "orcid", "affiliations", "field_hints", "notes", "created_at", "updated_at") VALUES (4, 'group', 'Turbulence reading group', '[{"value": "Turbulence reading group", "script": "Latin"}]', '{}', NULL, '[]', '[]', NULL, '2026-02-01 07:28:00', '2026-02-01 07:28:00');

-- watch_profile_members: 2 row(s)
INSERT INTO "watch_profile_members" ("profile_id", "member_profile_id") VALUES (4, 1);
INSERT INTO "watch_profile_members" ("profile_id", "member_profile_id") VALUES (4, 2);

-- watch_profile_matches: 4 row(s)
INSERT INTO "watch_profile_matches" ("document_id", "profile_id", "basis", "matched_author", "evidence", "first_seen_at") VALUES (1, 1, 'identifier', 'Ada Lovelace', '{"orcid": "0000-0002-1825-0097"}', '2026-02-01 05:37:00');
INSERT INTO "watch_profile_matches" ("document_id", "profile_id", "basis", "matched_author", "evidence", "first_seen_at") VALUES (3, 2, 'name+affiliation', '山田 太郎', '{"affiliation": "\u6771\u4eac\u5927\u5b66"}', '2026-02-01 06:14:00');
INSERT INTO "watch_profile_matches" ("document_id", "profile_id", "basis", "matched_author", "evidence", "first_seen_at") VALUES (8, 1, 'name_only', 'Ada Lovelace', NULL, '2026-02-01 06:51:00');
INSERT INTO "watch_profile_matches" ("document_id", "profile_id", "basis", "matched_author", "evidence", "first_seen_at") VALUES (1, 3, 'name+affiliation', 'Alan Turing', '{"affiliation": "National Physical Laboratory"}', '2026-02-01 07:28:00');

-- document_categories: 13 row(s)
INSERT INTO "document_categories" ("document_id", "category") VALUES (1, 'cs.LG');
INSERT INTO "document_categories" ("document_id", "category") VALUES (1, 'physics.flu-dyn');
INSERT INTO "document_categories" ("document_id", "category") VALUES (2, 'cs.LG');
INSERT INTO "document_categories" ("document_id", "category") VALUES (3, 'q-bio.BM');
INSERT INTO "document_categories" ("document_id", "category") VALUES (4, 'cond-mat.mtrl-sci');
INSERT INTO "document_categories" ("document_id", "category") VALUES (6, 'soc');
INSERT INTO "document_categories" ("document_id", "category") VALUES (7, 'q-bio.OT');
INSERT INTO "document_categories" ("document_id", "category") VALUES (7, 'stat.AP');
INSERT INTO "document_categories" ("document_id", "category") VALUES (8, 'cs.LG');
INSERT INTO "document_categories" ("document_id", "category") VALUES (9, 'q-bio.BM');
INSERT INTO "document_categories" ("document_id", "category") VALUES (10, 'hep-ex');
INSERT INTO "document_categories" ("document_id", "category") VALUES (12, 'psy');
INSERT INTO "document_categories" ("document_id", "category") VALUES (12, 'stat.AP');

-- execution_sources: 6 row(s)
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (1, 'arxiv', 'ok', 9, NULL, NULL, NULL, NULL, '2026-02-01 05:37:00');
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (1, 'openalex', 'ok', 3, NULL, NULL, NULL, NULL, '2026-02-01 06:14:00');
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (1, 'semantic_scholar', 'error', 0, 'HTTP 503 from the upstream', NULL, 'upstream_error', '503 after 3 retries', '2026-02-01 06:51:00');
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (1, 'ieee', 'skipped_missing_key', 0, NULL, 'IEEE_API_KEY', 'missing_credential', 'no key configured for this source', '2026-02-01 07:28:00');
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (4, 'pubmed', 'cancelled', 0, NULL, NULL, 'cancelled', 'cancelled mid-query', '2026-02-01 08:05:00');
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (3, 'europepmc', 'ok', 7, NULL, NULL, NULL, NULL, '2026-02-01 08:42:00');

-- execution_ai: 5 row(s)
INSERT INTO "execution_ai" ("execution_id", "lane_index", "lane_label", "lane_kind", "provider", "model", "credential_alias", "outcome", "error_kind", "http_status", "safe_message", "docs_attempted", "docs_succeeded", "started_at", "ended_at") VALUES (1, 0, 'Claude subscription', 'subscription', 'anthropic', 'claude-3-5-sonnet', NULL, 'ok', NULL, NULL, NULL, 9, 9, '2026-02-01 05:37:00', '2026-02-01 05:37:00');
INSERT INTO "execution_ai" ("execution_id", "lane_index", "lane_label", "lane_kind", "provider", "model", "credential_alias", "outcome", "error_kind", "http_status", "safe_message", "docs_attempted", "docs_succeeded", "started_at", "ended_at") VALUES (1, 1, 'OpenAI key', 'api_key', 'openai', 'gpt-4o-mini', 'work-key', 'partial', 'content_filter', 200, '3 abstracts were refused', 9, 6, '2026-02-01 06:14:00', '2026-02-01 06:14:00');
INSERT INTO "execution_ai" ("execution_id", "lane_index", "lane_label", "lane_kind", "provider", "model", "credential_alias", "outcome", "error_kind", "http_status", "safe_message", "docs_attempted", "docs_succeeded", "started_at", "ended_at") VALUES (1, 2, 'Local model', 'local', 'ollama', 'llama3', NULL, 'failed', 'connection_refused', NULL, 'no local runtime listening', 9, 0, '2026-02-01 06:51:00', '2026-02-01 06:51:00');
INSERT INTO "execution_ai" ("execution_id", "lane_index", "lane_label", "lane_kind", "provider", "model", "credential_alias", "outcome", "error_kind", "http_status", "safe_message", "docs_attempted", "docs_succeeded", "started_at", "ended_at") VALUES (1, 3, 'Spare key', 'api_key', 'openai', NULL, 'spare-key', 'skipped', NULL, NULL, NULL, 0, 0, '2026-02-01 07:28:00', '2026-02-01 07:28:00');
INSERT INTO "execution_ai" ("execution_id", "lane_index", "lane_label", "lane_kind", "provider", "model", "credential_alias", "outcome", "error_kind", "http_status", "safe_message", "docs_attempted", "docs_succeeded", "started_at", "ended_at") VALUES (5, 0, 'Claude subscription', 'subscription', 'anthropic', 'claude-3-5-sonnet', NULL, 'running', NULL, NULL, NULL, 0, 0, '2026-02-01 08:05:00', NULL);

-- watchdog_mutes: 2 row(s)
INSERT INTO "watchdog_mutes" ("finding_key", "muted_at", "note") VALUES ('source_silent:zenodo', '2026-02-01 05:37:00', 'Known: we stopped watching datasets.');
INSERT INTO "watchdog_mutes" ("finding_key", "muted_at", "note") VALUES ('routine_never_fired:3', '2026-02-01 06:14:00', NULL);

-- document_lifecycle: 3 row(s)
INSERT INTO "document_lifecycle" ("document_id", "kind", "severity", "notice_key", "label", "notice_doi", "notice_url", "notice_date", "detail", "provider", "provider_source", "first_seen_at") VALUES (7, 'retraction', 'critical', 'crossref:10.1000/retraction.1', 'Retracted', '10.1000/retraction.1', 'https://example.org/notice/retraction-1', '2023-01-09', 'Retracted by the publisher.', 'crossref', 'crossref-update-feed', '2026-02-01 05:37:00');
INSERT INTO "document_lifecycle" ("document_id", "kind", "severity", "notice_key", "label", "notice_doi", "notice_url", "notice_date", "detail", "provider", "provider_source", "first_seen_at") VALUES (7, 'expression_of_concern', 'caution', 'crossref:10.1000/eoc.1', 'Expression of concern', NULL, 'https://example.org/notice/eoc-1', NULL, NULL, 'crossref', NULL, '2026-02-01 06:14:00');
INSERT INTO "document_lifecycle" ("document_id", "kind", "severity", "notice_key", "label", "notice_doi", "notice_url", "notice_date", "detail", "provider", "provider_source", "first_seen_at") VALUES (4, 'correction', 'informational', 'crossref:10.1000/correction.1', 'Correction', '10.1000/correction.1', 'https://example.org/notice/correction-1', '2024-09-01', 'Figure 2 axis label.', 'crossref', NULL, '2026-02-01 06:51:00');

-- document_lifecycle_checks: 3 row(s)
INSERT INTO "document_lifecycle_checks" ("document_id", "checked_at", "status", "error_message", "providers") VALUES (5, '2026-02-01 08:05:00', 'no_identifier', NULL, '[]');
INSERT INTO "document_lifecycle_checks" ("document_id", "checked_at", "status", "error_message", "providers") VALUES (7, '2026-02-01 09:19:00', 'ok', NULL, '["crossref", "europepmc"]');
INSERT INTO "document_lifecycle_checks" ("document_id", "checked_at", "status", "error_message", "providers") VALUES (10, '2026-02-01 11:10:00', 'error', 'HTTP 429 from the notice provider', '["crossref"]');

-- document_embeddings: 4 row(s)
INSERT INTO "document_embeddings" ("document_id", "model", "dims", "vector", "fields", "embedded_at") VALUES (1, 'all-MiniLM-L6-v2', 4, X'0001FEFF10203040000000007F808182', 'title+abstract', '2026-02-01 05:37:00');
INSERT INTO "document_embeddings" ("document_id", "model", "dims", "vector", "fields", "embedded_at") VALUES (2, 'all-MiniLM-L6-v2', 4, X'0001FEFF10203041000000007F808182', 'title+abstract', '2026-02-01 06:14:00');
INSERT INTO "document_embeddings" ("document_id", "model", "dims", "vector", "fields", "embedded_at") VALUES (3, 'all-MiniLM-L6-v2', 4, X'000102030405060708090A0B0C0D0E0F', 'title', '2026-02-01 06:51:00');
INSERT INTO "document_embeddings" ("document_id", "model", "dims", "vector", "fields", "embedded_at") VALUES (3, 'bge-small-en', 4, X'101112131415161718191A1B1C1D1E1F', 'title+abstract', '2026-02-01 07:28:00');

-- document_links: 3 row(s)
INSERT INTO "document_links" ("document_a", "document_b", "kind", "score", "method", "created_at") VALUES (1, 2, 'near_duplicate', 0.9912109375, 'cosine', '2026-02-01 05:37:00');
INSERT INTO "document_links" ("document_a", "document_b", "kind", "score", "method", "created_at") VALUES (1, 2, 'same_doi', 1.0, 'doi', '2026-02-01 06:14:00');
INSERT INTO "document_links" ("document_a", "document_b", "kind", "score", "method", "created_at") VALUES (1, 8, 'shared_author', NULL, 'author_overlap', '2026-02-01 06:51:00');

-- assistant_sessions: 2 row(s)
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (1, 'claude_cli', '11111111-2222-3333-4444-555555555555', 'claude-3-5-sonnet', 'What is new on turbulence?', '2026-02-01 05:37:00', '2026-02-01 05:37:00');
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (2, 'api_key', NULL, NULL, NULL, '2026-02-01 06:14:00', '2026-02-01 06:14:00');

-- assistant_messages: 3 row(s)
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (1, 1, 'system', 'You are resmon''s assistant.', NULL, NULL, NULL, NULL, NULL, '2026-02-01 05:37:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (2, 1, 'user', 'What is new on turbulence closures?', NULL, NULL, 41, NULL, NULL, '2026-02-01 06:14:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (3, 1, 'assistant', 'Three papers arrived this week — の詳細は以下。', '[{"name": "search_corpus", "input": {"query": "turbulence"}}]', '[{"name": "search_corpus", "count": 3}]', 41, 180, 0.0123, '2026-02-01 06:51:00');

-- AUTOINCREMENT high-water marks. Restored explicitly because
-- a deleted row leaves the sequence above the highest surviving id.
UPDATE sqlite_sequence SET seq = 3 WHERE name = 'assistant_messages';
UPDATE sqlite_sequence SET seq = 2 WHERE name = 'assistant_sessions';
UPDATE sqlite_sequence SET seq = 3 WHERE name = 'cloud_sync';
UPDATE sqlite_sequence SET seq = 13 WHERE name = 'documents';
UPDATE sqlite_sequence SET seq = 5 WHERE name = 'executions';
UPDATE sqlite_sequence SET seq = 4 WHERE name = 'routines';
UPDATE sqlite_sequence SET seq = 3 WHERE name = 'saved_configurations';
UPDATE sqlite_sequence SET seq = 4 WHERE name = 'watch_profiles';

COMMIT;
