import React from 'react';import {render,screen,fireEvent,act} from '@testing-library/react';
import SelectionDialog from '../components/Evidence/SelectionDialog';import {selectedApi,Preview} from '../api/selectedEvidence';import {Project,EvidenceFile,Member,SavedNote,Page} from '../api/evidence';import {ChoicesDescriptor} from '../components/Assistant/ComposerChoices';
const id=(n:number)=>`${n.toString().padStart(8,'0')}-1111-4111-8111-111111111111`;
const project={project_id:id(1),vault_id:id(2),revision:1} as Project;const file={file_id:id(3),version_id:id(4),vault_id:id(2),original_name:'selected.txt',media_type:'text/plain',sha256:'a'.repeat(64)} as EvidenceFile;
const descriptor:ChoicesDescriptor={version:1,default_request:{version:1,runtime:'claude_cli',provider:'claude_code',model:null,effort:null},default_error:null,connections:[{runtime:'claude_cli',provider:'claude_code',label:'Synthetic CLI',implemented:true,available:true,reason:'Synthetic only',effort_supported:true}],claude_aliases:['fable'],claude_efforts:['high'],limitations:'No live quality proof'};
const props={project,file,anchor:null,runtime:id(9),descriptor,files:{items:[{file_id:file.file_id,version_id:file.version_id,file}],has_more:false} as Page<Member>,notes:{items:[{note_id:id(5),file_id:file.file_id,version_id:file.version_id,file,revision:1,membership_state:'member',body:'LOCAL NOTE'}],has_more:false} as Page<SavedNote>,onNextFiles:jest.fn(),onNextNotes:jest.fn(),onClose:jest.fn(),onSend:jest.fn()};
const preview={preview_id:id(7),request_sha256:'b'.repeat(64),expires_at_utc:'future',request:{payload:{requested:{provider:'claude_code',runtime:'claude_cli'},coverage:{file_count:1,page_count:1,segment_count:1,source_bytes:5,note_count:0,note_bytes:0,files:[]},sources:[{source_id:'S01',original_name:'selected.txt',page_number:1,text:'<img src="bad">',version_id:file.version_id,start_codepoint:0,end_codepoint:15,source_sha256:'a'.repeat(64)}],notes:[],disclosure:{custom_endpoint:false,limitations:'Support unchecked',source_strings_may_contain_private_material:'Inspect before Send'}},system_text:'SYSTEM',user_prompt:'USER'}} as unknown as Preview;
afterEach(()=>jest.restoreAllMocks());
async function select(){fireEvent.click(screen.getByRole('button',{name:'Add selected.txt logical page 1'}));fireEvent.change(screen.getByLabelText('Question or briefing instruction'),{target:{value:'Question'}});fireEvent.click(screen.getByRole('button',{name:'Preview selected content'}));await screen.findByRole('heading',{name:'Inspect before Send'});}
it('defaults notes off, renders literal preview, and requires separate Send',async()=>{const prepare=jest.spyOn(selectedApi,'preview').mockResolvedValue(preview);const send=jest.fn().mockResolvedValue(undefined);const view=render(<SelectionDialog {...props} onSend={send}/>);await select();expect(prepare.mock.calls[0][3]).toEqual([]);expect(send).not.toHaveBeenCalled();expect(view.container.querySelector('img,script')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Send selected evidence'}));expect(send).toHaveBeenCalledWith(preview);});
it('closing preview sends nothing and editing an instruction invalidates consent',async()=>{jest.spyOn(selectedApi,'preview').mockResolvedValue(preview);const send=jest.fn();render(<SelectionDialog {...props} onSend={send}/>);await select();fireEvent.click(screen.getByRole('button',{name:'Close preview without sending'}));expect(screen.queryByRole('heading',{name:'Inspect before Send'})).toBeNull();expect(send).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Preview selected content'}));await screen.findByRole('heading',{name:'Inspect before Send'});fireEvent.change(screen.getByLabelText('Question or briefing instruction'),{target:{value:'Later question'}});expect(screen.queryByRole('button',{name:'Send selected evidence'})).toBeNull();});
it('retired preview and its error cannot arrive after Escape; focus returns to trigger',async()=>{let resolve!:(p:Preview)=>void;const prepare=jest.spyOn(selectedApi,'preview').mockImplementation(()=>new Promise(r=>{resolve=r;}));const trigger=document.createElement('button');document.body.append(trigger);trigger.focus();const close=jest.fn();const view=render(<SelectionDialog {...props} onClose={close}/>);fireEvent.click(screen.getByRole('button',{name:'Add selected.txt logical page 1'}));fireEvent.change(screen.getByLabelText('Question or briefing instruction'),{target:{value:'Question'}});fireEvent.click(screen.getByRole('button',{name:'Preview selected content'}));fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});expect(close).toHaveBeenCalledTimes(1);view.unmount();expect(prepare.mock.calls[0][7]?.aborted).toBe(true);await act(async()=>resolve(preview));expect(trigger).toHaveFocus();trigger.remove();});
