import {canonical,validateRequest,validateAnswer,selectedApi,Answer,RequestSnapshot} from '../api/selectedEvidence';
import {Project} from '../api/evidence';
import {webcrypto,createHash} from 'crypto';import {TextEncoder} from 'util';import {Buffer} from 'buffer';
const id=(n:number)=>`${n.toString().padStart(8,'0')}-1111-4111-8111-111111111111`;
const project={project_id:id(1),vault_id:id(2),revision:1} as Project;
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
function snapshot():RequestSnapshot{const source={source_id:'S01',file_id:id(3),version_id:id(4),vault_id:id(2),project_id:id(1),sha256:'a'.repeat(64),byte_size:50,media_type:'text/plain',original_name:'literal.txt',page_number:1,page_count:1,extraction_contract:'library-text-lf/v1',page_text_sha256:hash('😀 repeat repeat'),start_codepoint:0,end_codepoint:15,text:'😀 repeat repeat'};const payload={version:1,profile:'selected_evidence_v1',vault_id:id(2),project_id:id(1),project_revision:1,mode:'question',instruction:'What is selected?',requested:{version:1,runtime:'claude_cli',provider:'claude_code',requested_model:null,requested_effort:null,model_basis:'runtime_default',effort_basis:'runtime_default',binding_basis:'new'},sources:[{...source,source_sha256:hash(canonical(Object.fromEntries(Object.entries(source).filter(([k])=>k!=='source_id'))))}],notes:[],system_version:'selected-evidence/v1',system_sha256:hash('fixed synthetic system'),response_contract:{},coverage:{file_count:1,page_count:1,segment_count:1,source_bytes:new TextEncoder().encode(source.text).length,source_codepoints:15,note_count:0,note_bytes:0,files:[{file_id:id(3),version_id:id(4),known_page_count:1,selected_pages:[1],anchor_checked_pages:[1],unexamined_page_count:0}]},disclosure:{custom_endpoint:false,limitations:'Support unchecked',source_strings_may_contain_private_material:'Inspect the text',retained_digest_reads_selected_file_bytes:true,pdf_structure_examined_for_selected_pages:true}};const request_sha256=hash(canonical(payload)),user_prompt=canonical({request_sha256,payload});return {payload,request_sha256,user_prompt,user_sha256:hash(user_prompt),system_text:'fixed synthetic system',system_sha256:payload.system_sha256} as RequestSnapshot;}
function answer():Answer{const request=snapshot();return {contract_version:1,id:1,answer_id:id(5),vault_id:id(2),project_id:id(1),project_revision:1,request_sha256:request.request_sha256,mode:'question',state:'succeeded',cleanup_state:'confirmed',created_at_utc:'2026-09-12T00:00:00.000000+00:00',finished_at_utc:'2026-09-12T00:00:01.000000+00:00',started_at_utc:null,request,partial_text:'',reports:[],usage:null,validation:'exact_text_identity_only_support_unchecked',current_originals:'not_rechecked',limitations:'Support unchecked',error_code:null,error_message:null,result:{version:1,request_sha256:request.request_sha256,mode:'question',status:'answer',sections:[{kind:'summary',items:[{kind:'source_statement',text:'A contradictory claim remains support unchecked',citations:[{source_id:'S01',start_codepoint:9,end_codepoint:15,quote:'repeat'}],note_ids:[]}]}],limitations:[]}};}
beforeAll(()=>{Object.defineProperty(globalThis,'TextEncoder',{value:TextEncoder,configurable:true});Object.defineProperty(globalThis,'crypto',{value:{subtle:{digest:(a:string,d:ArrayBuffer)=>webcrypto.subtle.digest(a,Buffer.from(new Uint8Array(d)))}},configurable:true});});
it('checks frozen prompt hashes and the second Unicode occurrence without semantic promotion',async()=>{await expect(validateRequest(snapshot(),project)).resolves.toEqual(snapshot());await expect(validateAnswer(answer(),project)).resolves.toMatchObject({state:'succeeded'});});
it.each(['hash','quote','source','empty-citation','note','status','report','coverage','mode'])('refuses corrupt %s before display',async fault=>{const a=answer();const item=a.result!.sections[0].items[0];if(fault==='hash')a.request.user_prompt+='x';if(fault==='quote')item.citations[0].start_codepoint=2;if(fault==='source')item.citations[0].source_id='S99';if(fault==='empty-citation')item.citations=[];if(fault==='note')item.note_ids=[id(8)];if(fault==='status')a.result!.status='insufficient_evidence';if(fault==='report')a.reports=[{model:'x',source:'invented',observed_at_utc:'today'}];if(fault==='coverage')a.request.payload.coverage.source_bytes++;if(fault==='mode')a.mode='briefing';await expect(validateAnswer(a,project)).rejects.toThrow();});
it('rejects invalid scalars and refuses an ambient or reserved instance before setup contact',async()=>{for(const x of [NaN,Infinity,1.2,'\uD800'])expect(()=>canonical(x)).toThrow();global.fetch=jest.fn();for(const port of ['', '8742']){window.resmonAPI={getBackendPort:()=>port,platform:'test',versions:{node:'test',electron:'test'}};await expect(selectedApi.setup()).rejects.toThrow();}expect(fetch).not.toHaveBeenCalled();});
