import React,{useEffect,useRef,useState} from 'react';
import {Anchor,EvidenceFile,Project} from '../../api/evidence';
import {libraryApi} from '../../api/library';
import {Answer,Citation,Source} from '../../api/selectedEvidence';
import {downloadSelectedAnswer} from '../../lib/selectedEvidenceDownload';
import EvidenceReader from './EvidenceReader';
export interface CitationRange extends Anchor {file_id:string;version_id:string;sha256:string}
export default function AnswerView({project,answer}:{project:Project;answer:Answer}){
  const [citation,setCitation]=useState<{source:Source;quote:Citation}|null>(null),[file,setFile]=useState<EvidenceFile|null>(null),[error,setError]=useState(''),[download,setDownload]=useState(''),[saving,setSaving]=useState(false);const epoch=useRef(0),abort=useRef<AbortController|null>(null);
  useEffect(()=>{++epoch.current;setCitation(null);setFile(null);setError('');setDownload('');setSaving(false);return()=>{++epoch.current;abort.current?.abort();};},[answer.answer_id]);
  const open=async(s:Source,c:Citation)=>{const ticket=++epoch.current;setCitation({source:s,quote:c});setFile(null);setError('');try{const f=await libraryApi.detail(project.vault_id,s.file_id);if(ticket!==epoch.current)return;if(f.version_id!==s.version_id||f.sha256!==s.sha256)throw new Error('Current file identity differs. The frozen excerpt stays available; no latest-version fallback.');setFile(f);}catch(e){if(ticket===epoch.current)setError(e instanceof Error?e.message:'Current original unavailable; saved excerpt remains.');}};
  const save=async()=>{const selected=answer;const ticket=epoch.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setSaving(true);setDownload('Preparing the saved selected-text ZIP…');try{await downloadSelectedAnswer(project,selected,controller.signal);if(ticket===epoch.current)setDownload('The selected ZIP was handed to the browser download flow. Check the chosen destination.');}catch(e){if(ticket===epoch.current)setDownload(e instanceof Error?e.message:'ZIP download failed.');}finally{if(ticket===epoch.current&&abort.current===controller)setSaving(false);}};
  const range:CitationRange|undefined=citation?{file_id:citation.source.file_id,version_id:citation.source.version_id,sha256:citation.source.sha256,page_number:citation.source.page_number,extraction_contract:citation.source.extraction_contract,page_text_sha256:citation.source.page_text_sha256,start_codepoint:citation.quote.start_codepoint,end_codepoint:citation.quote.end_codepoint,quote:citation.quote.quote}:undefined;
  return <article className="selected-answer" aria-label="Selected evidence answer"><h3>{answer.mode==='briefing'?'Manual structured briefing':'Selected-evidence question'}</h3><p><strong>State:</strong> {answer.state} · local transport cleanup: {answer.cleanup_state}</p>
    <p className="selected-limits">Citations match selected text identity only. Semantic support, research quality and truth are unchecked.</p><p>{answer.limitations}</p>
    <p><strong>Requested:</strong> {answer.request.payload.requested.provider} · {answer.request.payload.requested.requested_model??'CLI default (unknown)'} · effort {answer.request.payload.requested.requested_effort??(answer.request.payload.requested.runtime==='api_key'?'not supported':'CLI default (unknown)')}</p>
    <p><strong>Reported model:</strong> {answer.reports.length?answer.reports.map(r=>`${r.model} (${r.source})`).join('; '):'Not reported'}. Reported effort and billing are unknown.</p>
    <details><summary>Reported usage</summary><pre>{answer.usage===null?'Not reported.':JSON.stringify(answer.usage,null,2)}</pre></details>
    <p className="evidence-identity">Answer {answer.answer_id}<br/>Request SHA256 {answer.request_sha256}</p><h4>Instruction</h4><p>{answer.request.payload.instruction}</p>
    {answer.error_message&&<p role="alert">{answer.error_message}</p>}
    {answer.result?answer.result.sections.map((s,index)=><section key={index}><h4>{s.kind}</h4>{s.items.map((item,i)=><div className="selected-answer-item" key={i}><p><strong>{item.kind==='note_summary'?'Owner-note summary':item.kind==='interpretation'?'Interpretation':item.kind==='question'?'Open question':'Source statement'} · support unchecked</strong></p><p>{item.text}</p>{item.note_ids.length>0&&<p>Saved local notes: {item.note_ids.join(', ')}</p>}{item.citations.map((c,j)=>{const source=answer.request.payload.sources.find(x=>x.source_id===c.source_id)!;return <button key={j} onClick={()=>void open(source,c)} aria-label={`Open citation ${c.source_id} item ${index+1}-${i+1}-${j+1}`}>{c.source_id} · {source.original_name} · page {source.page_number} · exact quoted text</button>;})}</div>)}</section>):<section aria-label="Unvalidated answer text"><h4>Incomplete / unvalidated output</h4><pre>{answer.partial_text||'No durable text has been recorded.'}</pre></section>}
    {answer.result?.limitations.map((l,i)=><p key={i}>Limitation: {l}</p>)}
    <details><summary>Frozen source excerpts and owner notes</summary>{answer.request.payload.sources.map(s=><section key={s.source_id}><h4>{s.source_id} · {s.original_name} · page {s.page_number}</h4><pre>{s.text}</pre></section>)}{answer.request.payload.notes.map(n=><section key={n.note_id}><h4>Owner note · {n.note_id} · revision {n.revision}</h4><pre>{n.body}</pre></section>)}</details>
    <details><summary>Saved disclosure and page coverage</summary><pre>{JSON.stringify(answer.request.payload.coverage,null,2)}</pre><pre>{JSON.stringify(answer.request.payload.disclosure,null,2)}</pre></details>
    {citation&&<section aria-label="Saved citation excerpt"><h4>Frozen citation · {citation.source.source_id}</h4><pre>{citation.quote.quote}</pre><p>These are the saved request bytes. Opening the current reader requires a fresh exact identity/text check.</p>{error&&<p role="alert">{error}</p>}{file&&<EvidenceReader project={project} file={file} reopen={null} citation={range} onPassage={()=>{}} canSave={false}/>}</section>}
    <button disabled={saving} onClick={()=>void save()}>Export this answer and selected text</button>{download&&<p role="status">{download}</p>}
  </article>;
}
