-- A resmon corpus at schema 21, written by resmon v2.3.0's own code.
--
-- Release: tag v2.3.0
-- Source:  commit 0d41ab611f02e70eea40e1bbd6912df7cb5f295c
--          -- the release branch head, which is AHEAD of that tag. This dump
--          was not generated from the tag; the note below says why.
-- Generated by: fixtures/v2.3.0/generate_corpus.py (committed beside this file)
-- Regenerate:   python generate_corpus.py --source-tree <v2.3.0 checkout>
-- Verify:       python generate_corpus.py --source-tree <v2.3.0 checkout> --check
--
-- The commit named above is the head of the release branch this fixture was
-- committed on, not the v2.3.0 tag. It could not be the tag: the test that
-- calls in a schema's fixture debt fails on the commit that bumps APP_VERSION,
-- which is inside the release pull request, and the tag is only cut once that
-- request has merged. Everything below depends on schema-21 code alone, which
-- the squash commit and the tag carry unchanged; only this hash differs. The
-- post-tag follow-up regenerates this file from the tag itself, replaces the
-- hash, adds v2.3.0 to CI's tag-fetch loop and sets RESMON_REQUIRE_V230_TAG.
-- Until then the regeneration case skips for v2.3.0, because the tag it would
-- check out is not there.
--
-- The standing rule in docs/release-verification.md: every release that ships
-- a schema leaves a corpus its own code wrote, so the next release can prove
-- that a database a *released* resmon produced survives the migrations it
-- ships. v2.3.0 shipped schema 21 and nothing migrates past it yet, so the
-- walk this file serves today is 21 -> 21: one `init_db` over it must change
-- no row, no object and no schema marker. `test_cumulative_upgrade.py`
-- executes this file and checks exactly that, the way a user's first launch
-- after an update does. The same file's 18 -> 21 walk -- the one a v2.2.0 user
-- actually takes -- runs over the v2.2.0 fixture, which is untouched here.
--
-- Everything here is synthetic. No row is read from, copied from or derived
-- from any real corpus.
--
-- What is deliberately not in this file:
--   * the fts5 shadow tables (`documents_fts_{config,content,data,docsize,idx}`)
--     and `sqlite_sequence`'s CREATE -- SQLite makes both for itself. The
--     three `documents_fts_insert/_delete/_update` triggers ARE resmon's and
--     are here; they are what repopulates the search index when the documents
--     below are inserted.
--   * live timestamps. Clock columns are rewritten from each row's rowid --
--     in SQLite's `datetime('now')` shape for schema 13's columns and in the
--     six-digit UTC shape `evidence.timestamp` requires for the `*_at_utc`
--     columns added since -- and the generator then fails if any value from
--     the run's own clock survives.
--   * the UUID4s Library, Evidence, the selected-answer lane, the assistant
--     session store and `runtime_identity` mint, and the vault's absolute
--     path. Both are rewritten to values derived from where they appear, so a
--     regeneration can be diffed and no directory from the generating machine
--     is published.
--   * process ids. `executions.owner_pid` and `deliveries.owner_pid` are the
--     generating process's, and are rewritten from each row's rowid.
--   * `routine_missed_fires.disposition = 'skipped'`. The value is in the
--     CHECK's vocabulary and nothing in v2.3.0 writes it, so no corpus this
--     release wrote can hold one.

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

CREATE TABLE documents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_repository TEXT NOT NULL,
    external_id TEXT NOT NULL,
    doi TEXT,
    title TEXT NOT NULL,
    authors TEXT,
    abstract TEXT,
    publication_date TEXT,
    url TEXT,
    categories TEXT,
    metadata_hash TEXT NOT NULL,
    first_seen_at TEXT NOT NULL DEFAULT (datetime('now')),
    pub_sort TEXT GENERATED ALWAYS AS (COALESCE(publication_date, '')) VIRTUAL,
    UNIQUE(source_repository, external_id)
);
CREATE TABLE execution_documents (
    execution_id INTEGER NOT NULL,
    document_id INTEGER NOT NULL,
    is_new INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (execution_id, document_id),
    FOREIGN KEY (execution_id) REFERENCES executions(id) ON DELETE CASCADE,
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE TABLE routines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    schedule_cron TEXT NOT NULL,
    parameters TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    email_enabled INTEGER NOT NULL DEFAULT 0,
    email_ai_summary_enabled INTEGER NOT NULL DEFAULT 0,
    ai_enabled INTEGER NOT NULL DEFAULT 0,
    notify_on_complete INTEGER NOT NULL DEFAULT 0,
    ai_settings TEXT,
    storage_settings TEXT,
    -- Free text: what this routine is actually looking for, in the user's own
    -- words. The keyword string is what resmon *sends*; this is what the user
    -- *means*, and the coverage audit needs the second to judge the first. It
    -- is optional and defaults to nothing rather than to the keyword string,
    -- because "the user wrote this" and "we reused the query" are different
    -- facts and the audit says which one it is working from.
    intent TEXT,
    execution_location TEXT NOT NULL DEFAULT 'local'
        CHECK (execution_location IN ('local', 'cloud')),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_executed_at TEXT
);
CREATE TABLE saved_configurations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    config_type TEXT NOT NULL CHECK(config_type IN ('manual_dive', 'manual_sweep', 'routine')),
    parameters TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE cloud_sync (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    provider TEXT NOT NULL DEFAULT 'google_drive',
    account_info TEXT,
    is_linked INTEGER NOT NULL DEFAULT 0,
    auto_backup_enabled INTEGER NOT NULL DEFAULT 0,
    last_sync_at TEXT,
    sync_status TEXT DEFAULT 'idle' CHECK(sync_status IN ('idle', 'syncing', 'error'))
);
CREATE TABLE app_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
CREATE TABLE document_authors (
    document_id       INTEGER NOT NULL,
    author            TEXT NOT NULL,
    -- Schema 13 (2.1). All three are nullable and are NULL far more often than
    -- not: measured on 2026-09-06, OpenAlex carried an ORCID on 9 of 17
    -- authorships and Crossref on 2 of 84. NULL means **the source did not
    -- say**, never "this person has no ORCID", and nothing downstream may read
    -- it the second way.
    orcid             TEXT,
    affiliation       TEXT,
    -- The source's own author id, prefixed with its slug so two sources' ids
    -- can never be compared by accident: `semantic_scholar:1751762`.
    source_author_id  TEXT,
    PRIMARY KEY (document_id, author),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_document_authors_orcid
    ON document_authors(orcid) WHERE orcid IS NOT NULL;
CREATE INDEX idx_document_authors_author
    ON document_authors(author);
CREATE TABLE watch_profiles (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    kind          TEXT NOT NULL CHECK (kind IN ('person', 'institution', 'group')),
    display_name  TEXT NOT NULL,
    -- The canonical name plus aliases, as JSON: [{"value": ..., "script": ...}].
    names         TEXT NOT NULL DEFAULT '[]',
    -- {"orcid": {"value": ..., "cited": ...}, "openalex": {...}, ...}. Every
    -- identifier carries where the user got it, because an identifier nobody
    -- can trace is an assertion.
    identifiers   TEXT NOT NULL DEFAULT '{}',
    orcid         TEXT,
    affiliations  TEXT NOT NULL DEFAULT '[]',
    -- Keywords used **only** to disambiguate, never to search: a profile is a
    -- person, and narrowing their papers by topic would silently hide their work.
    field_hints   TEXT NOT NULL DEFAULT '[]',
    notes         TEXT,
    created_at    TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_watch_profiles_orcid
    ON watch_profiles(orcid) WHERE orcid IS NOT NULL;
CREATE TABLE watch_profile_members (
    profile_id        INTEGER NOT NULL,
    member_profile_id INTEGER NOT NULL,
    PRIMARY KEY (profile_id, member_profile_id),
    FOREIGN KEY (profile_id) REFERENCES watch_profiles(id) ON DELETE CASCADE,
    FOREIGN KEY (member_profile_id) REFERENCES watch_profiles(id) ON DELETE CASCADE
);
CREATE TABLE watch_profile_matches (
    document_id     INTEGER NOT NULL,
    profile_id      INTEGER NOT NULL,
    basis           TEXT NOT NULL
                    CHECK (basis IN ('identifier', 'name+affiliation', 'name_only')),
    matched_author  TEXT NOT NULL,
    evidence        TEXT,
    first_seen_at   TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (document_id, profile_id),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    FOREIGN KEY (profile_id) REFERENCES watch_profiles(id) ON DELETE CASCADE
);
CREATE INDEX idx_watch_profile_matches_profile
    ON watch_profile_matches(profile_id, first_seen_at DESC);
CREATE TABLE document_categories (
    document_id INTEGER NOT NULL,
    category    TEXT NOT NULL,
    PRIMARY KEY (document_id, category),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_document_categories_category
    ON document_categories(category);
CREATE INDEX idx_documents_source
    ON documents(source_repository);
CREATE INDEX idx_documents_first_seen
    ON documents(first_seen_at);
CREATE TABLE execution_sources (
    execution_id    INTEGER NOT NULL,
    source          TEXT NOT NULL,
    status          TEXT NOT NULL
        CHECK (status IN ('ok', 'error', 'skipped_missing_key', 'cancelled')),
    result_count    INTEGER NOT NULL DEFAULT 0,
    error_message   TEXT,
    credential_name TEXT,
    zero_reason     TEXT,
    zero_detail     TEXT,
    recorded_at     TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (execution_id, source),
    FOREIGN KEY (execution_id) REFERENCES executions(id) ON DELETE CASCADE
);
CREATE INDEX idx_execution_sources_source
    ON execution_sources(source);
CREATE TABLE execution_ai (
    execution_id    INTEGER NOT NULL,
    lane_index      INTEGER NOT NULL,
    lane_label      TEXT NOT NULL,
    lane_kind       TEXT NOT NULL
        CHECK (lane_kind IN ('subscription', 'api_key', 'local')),
    provider        TEXT NOT NULL,
    model           TEXT,
    credential_alias TEXT,
    outcome         TEXT NOT NULL
        CHECK (outcome IN ('running', 'ok', 'partial', 'failed', 'skipped')),
    error_kind      TEXT,
    http_status     INTEGER,
    safe_message    TEXT,
    docs_attempted  INTEGER NOT NULL DEFAULT 0,
    docs_succeeded  INTEGER NOT NULL DEFAULT 0,
    started_at      TEXT NOT NULL DEFAULT (datetime('now')),
    ended_at        TEXT,
    PRIMARY KEY (execution_id, lane_index),
    FOREIGN KEY (execution_id) REFERENCES executions(id) ON DELETE CASCADE
);
CREATE INDEX idx_execution_ai_exec
    ON execution_ai(execution_id);
CREATE TABLE watchdog_mutes (
    finding_key TEXT PRIMARY KEY,
    muted_at    TEXT NOT NULL DEFAULT (datetime('now')),
    note        TEXT
);
CREATE TABLE document_lifecycle (
    document_id     INTEGER NOT NULL,
    kind            TEXT NOT NULL,
    severity        TEXT NOT NULL
        CHECK (severity IN ('critical', 'caution', 'informational')),
    notice_key      TEXT NOT NULL,
    label           TEXT,
    notice_doi      TEXT,
    notice_url      TEXT NOT NULL,
    notice_date     TEXT,
    detail          TEXT,
    provider        TEXT NOT NULL,
    provider_source TEXT,
    first_seen_at   TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (document_id, kind, notice_key),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_document_lifecycle_severity
    ON document_lifecycle(severity);
CREATE TABLE document_lifecycle_checks (
    document_id   INTEGER PRIMARY KEY,
    checked_at    TEXT NOT NULL DEFAULT (datetime('now')),
    status        TEXT NOT NULL
        CHECK (status IN ('ok', 'no_identifier', 'error')),
    error_message TEXT,
    providers     TEXT,
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE TABLE document_embeddings (
    document_id INTEGER NOT NULL,
    model       TEXT NOT NULL,
    dims        INTEGER NOT NULL,
    vector      BLOB NOT NULL,
    fields      TEXT NOT NULL,
    embedded_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (document_id, model),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_document_embeddings_model
    ON document_embeddings(model);
CREATE TABLE document_links (
    document_a  INTEGER NOT NULL,
    document_b  INTEGER NOT NULL,
    kind        TEXT NOT NULL,
    score       REAL,
    method      TEXT NOT NULL,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (document_a, document_b, kind),
    CHECK (document_a < document_b),
    FOREIGN KEY (document_a) REFERENCES documents(id) ON DELETE CASCADE,
    FOREIGN KEY (document_b) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_document_links_b
    ON document_links(document_b);
CREATE TABLE assistant_sessions (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    runtime         TEXT NOT NULL,
    cli_session_id  TEXT,
    model           TEXT,
    title           TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE assistant_messages (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id      INTEGER NOT NULL,
    role            TEXT NOT NULL
        CHECK (role IN ('user', 'assistant', 'system')),
    content         TEXT NOT NULL DEFAULT '',
    tool_calls      TEXT,
    tool_results    TEXT,
    input_tokens    INTEGER,
    output_tokens   INTEGER,
    cost_usd        REAL,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (session_id) REFERENCES assistant_sessions(id) ON DELETE CASCADE
);
CREATE INDEX idx_assistant_messages_session
    ON assistant_messages(session_id, id);
CREATE TABLE reading_queue (
    document_id INTEGER PRIMARY KEY,
    status      TEXT NOT NULL DEFAULT 'to_read'
        CHECK (status IN ('to_read', 'read')),
    saved_at    TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now')),
    read_at     TEXT,
    CHECK ((status = 'read' AND read_at IS NOT NULL)
           OR (status = 'to_read' AND read_at IS NULL)),
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);
CREATE INDEX idx_reading_queue_status_saved
    ON reading_queue(status, saved_at DESC, document_id DESC);
CREATE INDEX idx_documents_pubsort ON documents(pub_sort DESC, id DESC);
CREATE VIRTUAL TABLE documents_fts USING fts5(
                title, abstract, authors,
                content='documents',
                content_rowid='id',
                tokenize='unicode61 remove_diacritics 2'
            );
CREATE TRIGGER documents_fts_insert AFTER INSERT ON documents BEGIN
            INSERT INTO documents_fts(rowid, title, abstract, authors)
            VALUES (new.id, new.title, new.abstract, new.authors);
        END;
CREATE TRIGGER documents_fts_delete AFTER DELETE ON documents BEGIN
            INSERT INTO documents_fts(documents_fts, rowid, title, abstract, authors)
            VALUES ('delete', old.id, old.title, old.abstract, old.authors);
        END;
CREATE TRIGGER documents_fts_update AFTER UPDATE ON documents BEGIN
            INSERT INTO documents_fts(documents_fts, rowid, title, abstract, authors)
            VALUES ('delete', old.id, old.title, old.abstract, old.authors);
            INSERT INTO documents_fts(rowid, title, abstract, authors)
            VALUES (new.id, new.title, new.abstract, new.authors);
        END;
CREATE TABLE assistant_session_choices (
        session_id INTEGER PRIMARY KEY REFERENCES assistant_sessions(id) ON DELETE CASCADE,
        version INTEGER NOT NULL CHECK(version=1),
        runtime TEXT NOT NULL CHECK(runtime IN ('claude_cli','api_key')),
        provider TEXT NOT NULL,
        requested_model TEXT,
        requested_effort TEXT CHECK(requested_effort IS NULL OR requested_effort IN ('low','medium','high','xhigh','max')),
        model_basis TEXT NOT NULL CHECK(model_basis IN ('explicit','settings_default','runtime_default')),
        effort_basis TEXT NOT NULL CHECK(effort_basis IN ('explicit','settings_default','runtime_default','not_supported')),
        route_digest TEXT NOT NULL,
        binding_basis TEXT NOT NULL CHECK(binding_basis IN ('new','legacy_confirmed')),
        created_at_utc TEXT NOT NULL,
        CHECK(runtime != 'api_key' OR requested_effort IS NULL)
    );
CREATE TABLE assistant_turn_choices (
        user_message_id INTEGER PRIMARY KEY REFERENCES assistant_messages(id) ON DELETE CASCADE,
        assistant_message_id INTEGER REFERENCES assistant_messages(id) ON DELETE SET NULL,
        version INTEGER NOT NULL CHECK(version=1),
        requested_json TEXT NOT NULL,
        reported_json TEXT NOT NULL DEFAULT '[]',
        created_at_utc TEXT NOT NULL
    );
CREATE UNIQUE INDEX idx_assistant_turn_choices_assistant_message
        ON assistant_turn_choices(assistant_message_id) WHERE assistant_message_id IS NOT NULL;
CREATE TABLE library_vault (
    singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
    vault_id TEXT NOT NULL UNIQUE,
    root_path TEXT NOT NULL,
    created_at_utc TEXT NOT NULL
);
CREATE TABLE library_files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id TEXT NOT NULL UNIQUE,
    version_id TEXT NOT NULL UNIQUE,
    vault_id TEXT NOT NULL REFERENCES library_vault(vault_id) ON DELETE RESTRICT,
    sha256 TEXT NOT NULL CHECK (length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'),
    byte_size INTEGER NOT NULL CHECK (byte_size > 0 AND byte_size <= 67108864),
    media_type TEXT NOT NULL CHECK (media_type IN ('application/pdf', 'text/plain', 'text/markdown')),
    original_name TEXT NOT NULL,
    relative_path TEXT NOT NULL UNIQUE,
    created_at_utc TEXT NOT NULL,
    UNIQUE(vault_id, sha256)
);
CREATE TABLE library_file_documents (
    file_id TEXT NOT NULL REFERENCES library_files(file_id) ON DELETE RESTRICT,
    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    linked_at_utc TEXT NOT NULL,
    PRIMARY KEY (file_id, document_id)
);
CREATE INDEX idx_library_file_documents_document ON library_file_documents(document_id);
CREATE TABLE evidence_projects (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 project_id TEXT NOT NULL UNIQUE,
 vault_id TEXT NOT NULL REFERENCES library_vault(vault_id) ON DELETE RESTRICT,
 name TEXT NOT NULL CHECK(length(name) BETWEEN 1 AND 120),
 revision INTEGER NOT NULL CHECK(revision >= 1),
 created_at_utc TEXT NOT NULL,
 updated_at_utc TEXT NOT NULL
);
CREATE TABLE evidence_project_files (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 project_id TEXT NOT NULL REFERENCES evidence_projects(project_id) ON DELETE RESTRICT,
 file_id TEXT NOT NULL REFERENCES library_files(file_id) ON DELETE RESTRICT,
 version_id TEXT NOT NULL REFERENCES library_files(version_id) ON DELETE RESTRICT,
 added_at_utc TEXT NOT NULL,
 UNIQUE(project_id, file_id)
);
CREATE TABLE evidence_notes (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 note_id TEXT NOT NULL UNIQUE,
 project_id TEXT NOT NULL REFERENCES evidence_projects(project_id) ON DELETE RESTRICT,
 file_id TEXT NOT NULL REFERENCES library_files(file_id) ON DELETE RESTRICT,
 version_id TEXT NOT NULL REFERENCES library_files(version_id) ON DELETE RESTRICT,
 kind TEXT NOT NULL CHECK(kind IN ('note', 'passage')),
 body TEXT NOT NULL CHECK(length(body) <= 20000),
 page_number INTEGER,
 extraction_contract TEXT,
 page_text_sha256 TEXT,
 start_codepoint INTEGER,
 end_codepoint INTEGER,
 quote TEXT,
 revision INTEGER NOT NULL CHECK(revision >= 1),
 created_at_utc TEXT NOT NULL,
 updated_at_utc TEXT NOT NULL,
 CHECK (
  (kind = 'note' AND length(body) >= 1 AND page_number IS NULL AND extraction_contract IS NULL
   AND page_text_sha256 IS NULL AND start_codepoint IS NULL AND end_codepoint IS NULL AND quote IS NULL)
  OR
  (kind = 'passage' AND page_number IS NOT NULL AND page_number >= 1 AND extraction_contract IS NOT NULL
   AND page_text_sha256 IS NOT NULL AND length(page_text_sha256) = 64 AND page_text_sha256 NOT GLOB '*[^0-9a-f]*'
   AND start_codepoint IS NOT NULL AND end_codepoint IS NOT NULL AND quote IS NOT NULL AND start_codepoint >= 0 AND end_codepoint > start_codepoint
   AND length(quote) BETWEEN 1 AND 20000 AND end_codepoint - start_codepoint = length(quote))
 )
);
CREATE INDEX idx_evidence_project_files_order ON evidence_project_files(project_id, id);
CREATE INDEX idx_evidence_notes_order ON evidence_notes(project_id, id);
CREATE TABLE evidence_answers (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 answer_id TEXT NOT NULL UNIQUE,
 preview_id TEXT NOT NULL UNIQUE,
 vault_id TEXT NOT NULL REFERENCES library_vault(vault_id) ON DELETE RESTRICT,
 project_id TEXT NOT NULL REFERENCES evidence_projects(project_id) ON DELETE RESTRICT,
 project_revision INTEGER NOT NULL CHECK(project_revision >= 1),
 mode TEXT NOT NULL CHECK(mode IN ('question', 'briefing')),
 state TEXT NOT NULL CHECK(state IN ('admitted', 'running', 'succeeded', 'refused', 'failed', 'cancelled', 'interrupted')),
 request_json TEXT NOT NULL CHECK(length(CAST(request_json AS BLOB)) <= 262144),
 request_sha256 TEXT NOT NULL CHECK(length(request_sha256) = 64 AND request_sha256 NOT GLOB '*[^0-9a-f]*'),
 private_binding_json TEXT NOT NULL CHECK(length(CAST(private_binding_json AS BLOB)) <= 4096),
 private_native_session_id TEXT,
 owner_runtime_id TEXT NOT NULL,
 partial_text TEXT NOT NULL DEFAULT '' CHECK(length(CAST(partial_text AS BLOB)) <= 65536),
 result_json TEXT CHECK(result_json IS NULL OR length(CAST(result_json AS BLOB)) <= 65536),
 reports_json TEXT NOT NULL DEFAULT '[]' CHECK(length(CAST(reports_json AS BLOB)) <= 16384),
 usage_json TEXT CHECK(usage_json IS NULL OR length(CAST(usage_json AS BLOB)) <= 4096),
 error_code TEXT CHECK(error_code IS NULL OR length(error_code) <= 80),
 error_message TEXT CHECK(error_message IS NULL OR length(error_message) <= 1000),
 cleanup_state TEXT NOT NULL CHECK(cleanup_state IN ('not_started', 'pending', 'confirmed', 'unknown')),
 created_at_utc TEXT NOT NULL,
 started_at_utc TEXT,
 finished_at_utc TEXT,
 CHECK((state IN ('admitted','running') AND finished_at_utc IS NULL)
       OR (state IN ('succeeded','refused','failed','cancelled','interrupted') AND finished_at_utc IS NOT NULL)),
 CHECK(result_json IS NULL OR state IN ('succeeded','refused'))
);
CREATE INDEX idx_evidence_answers_project_order ON evidence_answers(project_id, id);
CREATE TABLE "executions" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    execution_type TEXT NOT NULL CHECK(execution_type IN ('deep_dive', 'deep_sweep', 'automated_sweep')),
    routine_id INTEGER,
    saved_configuration_id INTEGER,
    parameters TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT,
    status TEXT NOT NULL DEFAULT 'running' CHECK(status IN ('running', 'completed', 'failed', 'cancelled', 'interrupted')),
    result_count INTEGER DEFAULT 0,
    new_result_count INTEGER DEFAULT 0,
    log_path TEXT,
    result_path TEXT,
    error_message TEXT,
    progress_events TEXT,
    current_stage TEXT,
    owner_pid INTEGER,
    owner_runtime_id TEXT,
    last_seen_at_utc TEXT,
    interrupted_reason TEXT CHECK(interrupted_reason IS NULL OR interrupted_reason IN ('owner_dead', 'daemon_restart', 'unknown')),
    restarted_from INTEGER REFERENCES executions(id) ON DELETE SET NULL, cancel_reason TEXT, dedup_total INTEGER, dedup_new INTEGER, dedup_duplicates INTEGER, dedup_invalid INTEGER, dedup_cross_source INTEGER, request_id TEXT,
    FOREIGN KEY (routine_id) REFERENCES routines(id) ON DELETE SET NULL,
    FOREIGN KEY (saved_configuration_id) REFERENCES saved_configurations(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX idx_executions_request_id ON executions(request_id) WHERE request_id IS NOT NULL;
CREATE TABLE routine_missed_fires (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    routine_id INTEGER NOT NULL REFERENCES routines(id) ON DELETE CASCADE,
    due_at_utc TEXT NOT NULL,
    observed_at_utc TEXT NOT NULL,
    disposition TEXT NOT NULL DEFAULT 'recorded' CHECK(disposition IN ('recorded', 'ran_late', 'skipped')),
    UNIQUE(routine_id, due_at_utc)
);
CREATE INDEX idx_routine_missed_fires_routine ON routine_missed_fires(routine_id, due_at_utc);
CREATE TABLE routine_delivery_targets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    routine_id INTEGER NOT NULL REFERENCES routines(id) ON DELETE CASCADE,
    channel TEXT NOT NULL CHECK(channel IN ('email', 'folder', 'webhook', 'feed')),
    target TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    mode TEXT NOT NULL DEFAULT 'automatic' CHECK(mode IN ('automatic', 'review')),
    created_at_utc TEXT NOT NULL,
    updated_at_utc TEXT NOT NULL
);
CREATE INDEX idx_routine_delivery_targets_routine ON routine_delivery_targets(routine_id, id);
CREATE TABLE deliveries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    execution_id INTEGER NOT NULL REFERENCES executions(id) ON DELETE CASCADE,
    target_id INTEGER REFERENCES routine_delivery_targets(id) ON DELETE SET NULL,
    channel TEXT NOT NULL CHECK(channel IN ('email', 'folder', 'webhook', 'feed')),
    target_snapshot TEXT NOT NULL,
    state TEXT NOT NULL CHECK(state IN ('queued', 'awaiting_review', 'delivering', 'delivered', 'failed', 'skipped')),
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at_utc TEXT,
    last_error TEXT,
    artifact_sha256 TEXT,
    owner_pid INTEGER,
    owner_runtime_id TEXT,
    queued_at_utc TEXT NOT NULL,
    delivered_at_utc TEXT,
    UNIQUE(execution_id, target_id)
);
CREATE INDEX idx_deliveries_due ON deliveries(state, next_attempt_at_utc);
CREATE INDEX idx_deliveries_execution ON deliveries(execution_id);

-- documents: 12 row(s)
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (1, 'arxiv', '2401.00001', '10.48550/arXiv.2401.00001', 'Diffusion models for turbulent flow reconstruction', 'Ada Lovelace, Alan Turing, Grace Hopper', 'A study of diffusion models applied to turbulence.', '2026-01-15', 'https://example.org/arxiv/2401.00001', 'cs.LG, physics.flu-dyn', 'hash-arxiv-0001', '2026-02-01 05:37:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (2, 'openalex', 'W4391000001', '10.48550/arXiv.2401.00001', 'Diffusion models for turbulent flow reconstruction', 'Ada Lovelace, Alan Turing, Grace Hopper', 'A study of diffusion models applied to turbulence.', '2026-01-15', 'https://example.org/openalex/W4391000001', 'cs.LG', 'hash-arxiv-0001', '2026-02-01 06:14:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (3, 'pubmed', '39000001', '10.1000/pubmed.39000001', 'タンパク質折りたたみの速度論', '山田 太郎, Ana María Ñúñez-Olivér, Дмитрий Иванов', '折りたたみ速度の測定。', '2025-11-02', 'https://example.org/pubmed/39000001', 'q-bio.BM', 'hash-pubmed-0001', '2026-02-01 06:51:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (4, 'crossref', '10.1000/xyz123', '10.1000/xyz123', 'Ångström-scale imaging of catalytic surfaces', 'José González, Björn Östergaard', NULL, '2024-06-30', 'https://example.org/doi/10.1000/xyz123', 'cond-mat.mtrl-sci', 'hash-crossref-0001', '2026-02-01 07:28:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (5, 'zenodo', '10012345', NULL, 'Dataset: soil moisture readings, uncurated', NULL, NULL, NULL, NULL, NULL, 'hash-zenodo-0001', '2026-02-01 08:05:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (6, 'doaj', 'article-0001', '10.1000/doaj.0001', 'Open access publishing in the global south', 'Chimamanda Okeke, Ngũgĩ wa Thiong''o', 'A survey of open access mandates.', '2023-03-14', 'https://example.org/doaj/article-0001', 'soc', 'hash-doaj-0001', '2026-02-01 08:42:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (7, 'europepmc', 'PMC9000001', NULL, 'Retraction-prone preprints: a cohort study', 'Grace Hopper', 'A cohort study of preprints later retracted.', '2022-08-01', 'https://example.org/europepmc/PMC9000001', 'q-bio.OT, stat.AP', 'hash-europepmc-0001', '2026-02-01 09:19:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (8, 'semantic_scholar', 'corpusid:1751762', '10.1000/s2.1751762', 'Attention over sparse graphs', 'Ada Lovelace', 'Sparse attention for graph learning.', '2026-02-20', 'https://example.org/s2/1751762', 'cs.LG', 'hash-s2-0001', '2026-02-01 09:56:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (9, 'biorxiv', '2025.04.01.000001', '10.1101/2025.04.01.000001', 'A quote in the title: "folding" revisited, and a semicolon; too', 'O''Neill, Seán; D''Arcy, Máire', 'Punctuation that a naive SQL literal would break.', '2025-04-01', 'https://example.org/biorxiv/2025.04.01.000001', 'q-bio.BM', 'hash-biorxiv-0001', '2026-02-01 10:33:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (10, 'inspire_hep', '2700001', NULL, 'Constraints on axion-like particles', 'Lise Meitner, Chien-Shiung Wu', NULL, '2021-12-25', 'https://example.org/inspire/2700001', 'hep-ex', 'hash-inspire-0001', '2026-02-01 11:10:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (11, 'dryad', 'doi:10.5061/dryad.0001', '10.5061/dryad.0001', 'Supporting data for: axion constraints', 'Lise Meitner', 'Raw counts.', NULL, 'https://example.org/dryad/0001', NULL, 'hash-dryad-0001', '2026-02-01 11:47:00');
INSERT INTO "documents" ("id", "source_repository", "external_id", "doi", "title", "authors", "abstract", "publication_date", "url", "categories", "metadata_hash", "first_seen_at") VALUES (12, 'osf', 'preprint-0001', NULL, 'Preregistration and the replication rate', 'Barbara McClintock, 山田 花子', 'Preregistered studies replicate more often.', '2020-05-05', 'https://example.org/osf/preprint-0001', 'psy, stat.AP', 'hash-osf-0001', '2026-02-01 12:24:00');

-- execution_documents: 4 row(s)
INSERT INTO "execution_documents" ("execution_id", "document_id", "is_new") VALUES (1, 1, 1);
INSERT INTO "execution_documents" ("execution_id", "document_id", "is_new") VALUES (1, 2, 0);
INSERT INTO "execution_documents" ("execution_id", "document_id", "is_new") VALUES (1, 8, 1);
INSERT INTO "execution_documents" ("execution_id", "document_id", "is_new") VALUES (3, 7, 1);

-- routines: 2 row(s)
INSERT INTO "routines" ("id", "name", "schedule_cron", "parameters", "is_active", "email_enabled", "email_ai_summary_enabled", "ai_enabled", "notify_on_complete", "ai_settings", "storage_settings", "intent", "execution_location", "created_at", "updated_at", "last_executed_at") VALUES (1, 'Turbulence watch', '0 7 * * 1', '{"keywords": "diffusion turbulence", "sources": ["arxiv", "openalex"]}', 1, 1, 0, 1, 1, '{"lanes": ["subscription"]}', NULL, 'Anything new on learned turbulence closures.', 'local', '2026-02-01 05:37:00', '2026-02-01 05:37:00', NULL);
INSERT INTO "routines" ("id", "name", "schedule_cron", "parameters", "is_active", "email_enabled", "email_ai_summary_enabled", "ai_enabled", "notify_on_complete", "ai_settings", "storage_settings", "intent", "execution_location", "created_at", "updated_at", "last_executed_at") VALUES (2, 'Retraction watch', '0 8 * * *', '{"keywords": "retraction", "sources": ["europepmc"]}', 1, 0, 0, 1, 1, '{"lanes": ["subscription"]}', NULL, NULL, 'local', '2026-02-01 06:14:00', '2026-02-01 06:14:00', NULL);

-- saved_configurations: 3 row(s)
INSERT INTO "saved_configurations" ("id", "name", "config_type", "parameters", "created_at", "updated_at") VALUES (1, 'Weekly turbulence dive', 'manual_dive', '{"keywords": "diffusion turbulence", "sources": ["arxiv"]}', '2026-02-01 05:37:00', '2026-02-01 05:37:00');
INSERT INTO "saved_configurations" ("id", "name", "config_type", "parameters", "created_at", "updated_at") VALUES (2, 'Broad sweep', 'manual_sweep', '{"keywords": "protein folding", "sources": ["pubmed", "europepmc"]}', '2026-02-01 06:14:00', '2026-02-01 06:14:00');
INSERT INTO "saved_configurations" ("id", "name", "config_type", "parameters", "created_at", "updated_at") VALUES (3, 'Nightly routine config', 'routine', '{"keywords": "axion", "sources": ["inspire_hep"]}', '2026-02-01 06:51:00', '2026-02-01 06:51:00');

-- cloud_sync: 3 row(s)
INSERT INTO "cloud_sync" ("id", "provider", "account_info", "is_linked", "auto_backup_enabled", "last_sync_at", "sync_status") VALUES (1, 'google_drive', '{"email": "someone@example.org"}', 1, 1, '2026-02-01T05:00:00', 'idle');
INSERT INTO "cloud_sync" ("id", "provider", "account_info", "is_linked", "auto_backup_enabled", "last_sync_at", "sync_status") VALUES (2, 'google_drive', NULL, 0, 0, NULL, 'syncing');
INSERT INTO "cloud_sync" ("id", "provider", "account_info", "is_linked", "auto_backup_enabled", "last_sync_at", "sync_status") VALUES (3, 'google_drive', NULL, 0, 0, NULL, 'error');

-- app_settings: 12 row(s)
INSERT INTO "app_settings" ("key", "value") VALUES ('execution_sources_backfilled', '1');
INSERT INTO "app_settings" ("key", "value") VALUES ('dedup_columns_backfilled', '1');
INSERT INTO "app_settings" ("key", "value") VALUES ('schema_version', '21');
INSERT INTO "app_settings" ("key", "value") VALUES ('email_enabled', '0');
INSERT INTO "app_settings" ("key", "value") VALUES ('email_address', 'someone@example.org');
INSERT INTO "app_settings" ("key", "value") VALUES ('ai_provider', 'anthropic');
INSERT INTO "app_settings" ("key", "value") VALUES ('default_max_results', '50');
INSERT INTO "app_settings" ("key", "value") VALUES ('theme', 'dark');
INSERT INTO "app_settings" ("key", "value") VALUES ('export_footer', 'Compiled by resmon.
Don''t edit by hand.');
INSERT INTO "app_settings" ("key", "value") VALUES ('assistant_runtime', 'claude_cli');
INSERT INTO "app_settings" ("key", "value") VALUES ('assistant_model', 'claude-sonnet-4-5');
INSERT INTO "app_settings" ("key", "value") VALUES ('assistant_effort', 'high');

-- document_authors: 23 row(s)
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (1, 'Ada Lovelace', '0000-0002-1825-0097', 'Analytical Engine Group, London', 'arxiv:1');
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (1, 'Alan Turing', NULL, 'National Physical Laboratory', NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (1, 'Grace Hopper', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (2, 'Ada Lovelace', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (2, 'Alan Turing', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (2, 'Grace Hopper', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (3, '山田 太郎', '0000-0001-5109-3700', '東京大学, 理学部', 'pubmed:11');
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (3, 'Ana María Ñúñez-Olivér', NULL, 'Universidad de Chile', 'pubmed:12');
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (3, 'Дмитрий Иванов', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (4, 'José González', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (4, 'Björn Östergaard', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (6, 'Chimamanda Okeke', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (6, 'Ngũgĩ wa Thiong''o', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (7, 'Grace Hopper', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (8, 'Ada Lovelace', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (9, 'O''Neill', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (9, 'Seán; D''Arcy', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (9, 'Máire', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (10, 'Lise Meitner', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (10, 'Chien-Shiung Wu', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (11, 'Lise Meitner', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (12, 'Barbara McClintock', NULL, NULL, NULL);
INSERT INTO "document_authors" ("document_id", "author", "orcid", "affiliation", "source_author_id") VALUES (12, '山田 花子', NULL, NULL, NULL);

-- watch_profiles: 4 row(s)
INSERT INTO "watch_profiles" ("id", "kind", "display_name", "names", "identifiers", "orcid", "affiliations", "field_hints", "notes", "created_at", "updated_at") VALUES (1, 'person', 'Ada Lovelace', '[{"value": "Ada Lovelace", "script": "Latin"}, {"value": "A. Lovelace", "script": "Latin"}]', '{"orcid": {"value": "0000-0002-1825-0097", "cited": "https://example.org/orcid-page"}}', '0000-0002-1825-0097', '["Analytical Engine Group"]', '["machine learning"]', 'Watched since the corpus was started.', '2026-02-01 05:37:00', '2026-02-01 05:37:00');
INSERT INTO "watch_profiles" ("id", "kind", "display_name", "names", "identifiers", "orcid", "affiliations", "field_hints", "notes", "created_at", "updated_at") VALUES (2, 'person', '山田 太郎', '[{"value": "山田 太郎", "script": "Han"}, {"value": "Taro Yamada", "script": "Latin"}]', '{}', NULL, '["東京大学"]', '[]', NULL, '2026-02-01 06:14:00', '2026-02-01 06:14:00');
INSERT INTO "watch_profiles" ("id", "kind", "display_name", "names", "identifiers", "orcid", "affiliations", "field_hints", "notes", "created_at", "updated_at") VALUES (3, 'institution', 'National Physical Laboratory', '[{"value": "National Physical Laboratory", "script": "Latin"}]', '{"ror": {"value": "02mhbdp94", "cited": "https://example.org/ror-page"}}', NULL, '[]', '[]', NULL, '2026-02-01 06:51:00', '2026-02-01 06:51:00');
INSERT INTO "watch_profiles" ("id", "kind", "display_name", "names", "identifiers", "orcid", "affiliations", "field_hints", "notes", "created_at", "updated_at") VALUES (4, 'group', 'Turbulence reading group', '[{"value": "Turbulence reading group", "script": "Latin"}]', '{}', NULL, '[]', '[]', NULL, '2026-02-01 07:28:00', '2026-02-01 07:28:00');

-- watch_profile_members: 2 row(s)
INSERT INTO "watch_profile_members" ("profile_id", "member_profile_id") VALUES (4, 1);
INSERT INTO "watch_profile_members" ("profile_id", "member_profile_id") VALUES (4, 2);

-- watch_profile_matches: 4 row(s)
INSERT INTO "watch_profile_matches" ("document_id", "profile_id", "basis", "matched_author", "evidence", "first_seen_at") VALUES (1, 1, 'identifier', 'Ada Lovelace', '{"orcid": "0000-0002-1825-0097"}', '2026-02-01 05:37:00');
INSERT INTO "watch_profile_matches" ("document_id", "profile_id", "basis", "matched_author", "evidence", "first_seen_at") VALUES (3, 2, 'name+affiliation', '山田 太郎', '{"affiliation": "\u6771\u4eac\u5927\u5b66"}', '2026-02-01 06:14:00');
INSERT INTO "watch_profile_matches" ("document_id", "profile_id", "basis", "matched_author", "evidence", "first_seen_at") VALUES (8, 1, 'name_only', 'Ada Lovelace', NULL, '2026-02-01 06:51:00');
INSERT INTO "watch_profile_matches" ("document_id", "profile_id", "basis", "matched_author", "evidence", "first_seen_at") VALUES (1, 3, 'name+affiliation', 'Alan Turing', '{"affiliation": "National Physical Laboratory"}', '2026-02-01 07:28:00');

-- document_categories: 13 row(s)
INSERT INTO "document_categories" ("document_id", "category") VALUES (1, 'cs.LG');
INSERT INTO "document_categories" ("document_id", "category") VALUES (1, 'physics.flu-dyn');
INSERT INTO "document_categories" ("document_id", "category") VALUES (2, 'cs.LG');
INSERT INTO "document_categories" ("document_id", "category") VALUES (3, 'q-bio.BM');
INSERT INTO "document_categories" ("document_id", "category") VALUES (4, 'cond-mat.mtrl-sci');
INSERT INTO "document_categories" ("document_id", "category") VALUES (6, 'soc');
INSERT INTO "document_categories" ("document_id", "category") VALUES (7, 'q-bio.OT');
INSERT INTO "document_categories" ("document_id", "category") VALUES (7, 'stat.AP');
INSERT INTO "document_categories" ("document_id", "category") VALUES (8, 'cs.LG');
INSERT INTO "document_categories" ("document_id", "category") VALUES (9, 'q-bio.BM');
INSERT INTO "document_categories" ("document_id", "category") VALUES (10, 'hep-ex');
INSERT INTO "document_categories" ("document_id", "category") VALUES (12, 'psy');
INSERT INTO "document_categories" ("document_id", "category") VALUES (12, 'stat.AP');

-- execution_sources: 6 row(s)
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (1, 'arxiv', 'ok', 9, NULL, NULL, NULL, NULL, '2026-02-01 05:37:00');
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (1, 'openalex', 'ok', 3, NULL, NULL, NULL, NULL, '2026-02-01 06:14:00');
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (1, 'semantic_scholar', 'error', 0, 'HTTP 503 from the upstream', NULL, 'upstream_error', '503 after 3 retries', '2026-02-01 06:51:00');
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (1, 'ieee', 'skipped_missing_key', 0, NULL, 'IEEE_API_KEY', 'missing_credential', 'no key configured for this source', '2026-02-01 07:28:00');
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (4, 'pubmed', 'cancelled', 0, NULL, NULL, 'cancelled', 'cancelled mid-query', '2026-02-01 08:05:00');
INSERT INTO "execution_sources" ("execution_id", "source", "status", "result_count", "error_message", "credential_name", "zero_reason", "zero_detail", "recorded_at") VALUES (3, 'europepmc', 'ok', 7, NULL, NULL, NULL, NULL, '2026-02-01 08:42:00');

-- execution_ai: 5 row(s)
INSERT INTO "execution_ai" ("execution_id", "lane_index", "lane_label", "lane_kind", "provider", "model", "credential_alias", "outcome", "error_kind", "http_status", "safe_message", "docs_attempted", "docs_succeeded", "started_at", "ended_at") VALUES (1, 0, 'Claude subscription', 'subscription', 'anthropic', 'claude-3-5-sonnet', NULL, 'ok', NULL, NULL, NULL, 9, 9, '2026-02-01 05:37:00', '2026-02-01 05:37:00');
INSERT INTO "execution_ai" ("execution_id", "lane_index", "lane_label", "lane_kind", "provider", "model", "credential_alias", "outcome", "error_kind", "http_status", "safe_message", "docs_attempted", "docs_succeeded", "started_at", "ended_at") VALUES (1, 1, 'OpenAI key', 'api_key', 'openai', 'gpt-4o-mini', 'work-key', 'partial', 'content_filter', 200, '3 abstracts were refused', 9, 6, '2026-02-01 06:14:00', '2026-02-01 06:14:00');
INSERT INTO "execution_ai" ("execution_id", "lane_index", "lane_label", "lane_kind", "provider", "model", "credential_alias", "outcome", "error_kind", "http_status", "safe_message", "docs_attempted", "docs_succeeded", "started_at", "ended_at") VALUES (1, 2, 'Local model', 'local', 'ollama', 'llama3', NULL, 'failed', 'connection_refused', NULL, 'no local runtime listening', 9, 0, '2026-02-01 06:51:00', '2026-02-01 06:51:00');
INSERT INTO "execution_ai" ("execution_id", "lane_index", "lane_label", "lane_kind", "provider", "model", "credential_alias", "outcome", "error_kind", "http_status", "safe_message", "docs_attempted", "docs_succeeded", "started_at", "ended_at") VALUES (1, 3, 'Spare key', 'api_key', 'openai', NULL, 'spare-key', 'skipped', NULL, NULL, NULL, 0, 0, '2026-02-01 07:28:00', '2026-02-01 07:28:00');
INSERT INTO "execution_ai" ("execution_id", "lane_index", "lane_label", "lane_kind", "provider", "model", "credential_alias", "outcome", "error_kind", "http_status", "safe_message", "docs_attempted", "docs_succeeded", "started_at", "ended_at") VALUES (5, 0, 'Claude subscription', 'subscription', 'anthropic', 'claude-3-5-sonnet', NULL, 'running', NULL, NULL, NULL, 0, 0, '2026-02-01 08:05:00', NULL);

-- watchdog_mutes: 2 row(s)
INSERT INTO "watchdog_mutes" ("finding_key", "muted_at", "note") VALUES ('source_silent:zenodo', '2026-02-01 05:37:00', 'Known: we stopped watching datasets.');
INSERT INTO "watchdog_mutes" ("finding_key", "muted_at", "note") VALUES ('routine_never_fired:3', '2026-02-01 06:14:00', NULL);

-- document_lifecycle: 3 row(s)
INSERT INTO "document_lifecycle" ("document_id", "kind", "severity", "notice_key", "label", "notice_doi", "notice_url", "notice_date", "detail", "provider", "provider_source", "first_seen_at") VALUES (7, 'retraction', 'critical', 'crossref:10.1000/retraction.1', 'Retracted', '10.1000/retraction.1', 'https://example.org/notice/retraction-1', '2023-01-09', 'Retracted by the publisher.', 'crossref', 'crossref-update-feed', '2026-02-01 05:37:00');
INSERT INTO "document_lifecycle" ("document_id", "kind", "severity", "notice_key", "label", "notice_doi", "notice_url", "notice_date", "detail", "provider", "provider_source", "first_seen_at") VALUES (7, 'expression_of_concern', 'caution', 'crossref:10.1000/eoc.1', 'Expression of concern', NULL, 'https://example.org/notice/eoc-1', NULL, NULL, 'crossref', NULL, '2026-02-01 06:14:00');
INSERT INTO "document_lifecycle" ("document_id", "kind", "severity", "notice_key", "label", "notice_doi", "notice_url", "notice_date", "detail", "provider", "provider_source", "first_seen_at") VALUES (4, 'correction', 'informational', 'crossref:10.1000/correction.1', 'Correction', '10.1000/correction.1', 'https://example.org/notice/correction-1', '2024-09-01', 'Figure 2 axis label.', 'crossref', NULL, '2026-02-01 06:51:00');

-- document_lifecycle_checks: 3 row(s)
INSERT INTO "document_lifecycle_checks" ("document_id", "checked_at", "status", "error_message", "providers") VALUES (5, '2026-02-01 08:05:00', 'no_identifier', NULL, '[]');
INSERT INTO "document_lifecycle_checks" ("document_id", "checked_at", "status", "error_message", "providers") VALUES (7, '2026-02-01 09:19:00', 'ok', NULL, '["crossref", "europepmc"]');
INSERT INTO "document_lifecycle_checks" ("document_id", "checked_at", "status", "error_message", "providers") VALUES (10, '2026-02-01 11:10:00', 'error', 'HTTP 429 from the notice provider', '["crossref"]');

-- document_embeddings: 4 row(s)
INSERT INTO "document_embeddings" ("document_id", "model", "dims", "vector", "fields", "embedded_at") VALUES (1, 'all-MiniLM-L6-v2', 4, X'0001FEFF10203040000000007F808182', 'title+abstract', '2026-02-01 05:37:00');
INSERT INTO "document_embeddings" ("document_id", "model", "dims", "vector", "fields", "embedded_at") VALUES (2, 'all-MiniLM-L6-v2', 4, X'0001FEFF10203041000000007F808182', 'title+abstract', '2026-02-01 06:14:00');
INSERT INTO "document_embeddings" ("document_id", "model", "dims", "vector", "fields", "embedded_at") VALUES (3, 'all-MiniLM-L6-v2', 4, X'000102030405060708090A0B0C0D0E0F', 'title', '2026-02-01 06:51:00');
INSERT INTO "document_embeddings" ("document_id", "model", "dims", "vector", "fields", "embedded_at") VALUES (3, 'bge-small-en', 4, X'101112131415161718191A1B1C1D1E1F', 'title+abstract', '2026-02-01 07:28:00');

-- document_links: 3 row(s)
INSERT INTO "document_links" ("document_a", "document_b", "kind", "score", "method", "created_at") VALUES (1, 2, 'near_duplicate', 0.9912109375, 'cosine', '2026-02-01 05:37:00');
INSERT INTO "document_links" ("document_a", "document_b", "kind", "score", "method", "created_at") VALUES (1, 2, 'same_doi', 1.0, 'doi', '2026-02-01 06:14:00');
INSERT INTO "document_links" ("document_a", "document_b", "kind", "score", "method", "created_at") VALUES (1, 8, 'shared_author', NULL, 'author_overlap', '2026-02-01 06:51:00');

-- assistant_sessions: 10 row(s)
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (1, 'claude_cli', '00000000-0000-4000-8001-000000000001', 'claude-3-5-sonnet', 'What is new on turbulence?', '2026-02-01 05:37:00', '2026-02-01 05:37:00');
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (2, 'api_key', NULL, NULL, NULL, '2026-02-01 06:14:00', '2026-02-01 06:14:00');
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (3, 'claude_cli', '00000000-0000-4000-8001-000000000002', 'claude-opus-4-1', 'Explicit everything', '2026-02-01 06:51:00', '2026-02-01 06:51:00');
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (4, 'claude_cli', '00000000-0000-4000-8001-000000000003', 'claude-sonnet-4-5', 'Settings defaults', '2026-02-01 07:28:00', '2026-02-01 07:28:00');
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (5, 'claude_cli', '00000000-0000-4000-8001-000000000004', NULL, 'Runtime defaults', '2026-02-01 08:05:00', '2026-02-01 08:05:00');
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (6, 'api_key', NULL, 'gpt-4o-mini', 'An API connection', '2026-02-01 08:42:00', '2026-02-01 08:42:00');
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (7, 'claude_cli', '00000000-0000-4000-8001-000000000005', NULL, 'From before the choice was recorded', '2026-02-01 09:19:00', '2026-02-01 09:19:00');
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (8, 'claude_cli', '00000000-0000-4000-8001-000000000006', 'claude-opus-4-1', 'Effort medium', '2026-02-01 09:56:00', '2026-02-01 09:56:00');
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (9, 'claude_cli', '00000000-0000-4000-8001-000000000007', 'claude-opus-4-1', 'Effort high', '2026-02-01 10:33:00', '2026-02-01 10:33:00');
INSERT INTO "assistant_sessions" ("id", "runtime", "cli_session_id", "model", "title", "created_at", "updated_at") VALUES (10, 'claude_cli', '00000000-0000-4000-8001-000000000008', 'claude-opus-4-1', 'Effort xhigh', '2026-02-01 11:10:00', '2026-02-01 11:10:00');

-- assistant_messages: 11 row(s)
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (1, 1, 'system', 'You are resmon''s assistant.', NULL, NULL, NULL, NULL, NULL, '2026-02-01 05:37:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (2, 1, 'user', 'What is new on turbulence closures?', NULL, NULL, 41, NULL, NULL, '2026-02-01 06:14:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (3, 1, 'assistant', 'Three papers arrived this week — の詳細は以下。', '[{"name": "search_corpus", "input": {"query": "turbulence"}}]', '[{"name": "search_corpus", "count": 3}]', 41, 180, 0.0123, '2026-02-01 06:51:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (4, 3, 'user', 'Summarise the turbulence papers.', NULL, NULL, NULL, NULL, NULL, '2026-02-01 07:28:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (5, 3, 'assistant', 'Two of the three are the same paper under two ids.', NULL, NULL, 120, 64, 0.0041, '2026-02-01 08:05:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (6, 3, 'user', 'And the retractions?', NULL, NULL, NULL, NULL, NULL, '2026-02-01 08:42:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (7, 7, 'user', 'An older question.', NULL, NULL, NULL, NULL, NULL, '2026-02-01 09:19:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (8, 7, 'user', 'Still the same question?', NULL, NULL, NULL, NULL, NULL, '2026-02-01 09:56:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (9, 8, 'user', 'A question at medium.', NULL, NULL, NULL, NULL, NULL, '2026-02-01 10:33:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (10, 9, 'user', 'A question at high.', NULL, NULL, NULL, NULL, NULL, '2026-02-01 11:10:00');
INSERT INTO "assistant_messages" ("id", "session_id", "role", "content", "tool_calls", "tool_results", "input_tokens", "output_tokens", "cost_usd", "created_at") VALUES (11, 10, 'user', 'A question at xhigh.', NULL, NULL, NULL, NULL, NULL, '2026-02-01 11:47:00');

-- reading_queue: 3 row(s)
INSERT INTO "reading_queue" ("document_id", "status", "saved_at", "updated_at", "read_at") VALUES (1, 'to_read', '2026-02-01 05:37:00', '2026-02-01 05:37:00', NULL);
INSERT INTO "reading_queue" ("document_id", "status", "saved_at", "updated_at", "read_at") VALUES (3, 'read', '2026-02-01 06:51:00', '2026-02-01 06:51:00', '2026-02-01 06:51:00');
INSERT INTO "reading_queue" ("document_id", "status", "saved_at", "updated_at", "read_at") VALUES (5, 'to_read', '2026-02-01 08:05:00', '2026-02-01 08:05:00', NULL);

-- assistant_session_choices: 8 row(s)
INSERT INTO "assistant_session_choices" ("session_id", "version", "runtime", "provider", "requested_model", "requested_effort", "model_basis", "effort_basis", "route_digest", "binding_basis", "created_at_utc") VALUES (3, 1, 'claude_cli', 'claude_code', 'claude-opus-4-1', 'low', 'explicit', 'explicit', 'd296d7b87a7852dcaaac893a06c7d22fe55ee1bd14f120f5dd7581770df6a282', 'new', '2026-03-01T08:51:00.000003+00:00');
INSERT INTO "assistant_session_choices" ("session_id", "version", "runtime", "provider", "requested_model", "requested_effort", "model_basis", "effort_basis", "route_digest", "binding_basis", "created_at_utc") VALUES (4, 1, 'claude_cli', 'claude_code', 'claude-sonnet-4-5', 'high', 'settings_default', 'settings_default', 'd296d7b87a7852dcaaac893a06c7d22fe55ee1bd14f120f5dd7581770df6a282', 'new', '2026-03-01T09:28:00.000004+00:00');
INSERT INTO "assistant_session_choices" ("session_id", "version", "runtime", "provider", "requested_model", "requested_effort", "model_basis", "effort_basis", "route_digest", "binding_basis", "created_at_utc") VALUES (5, 1, 'claude_cli', 'claude_code', NULL, NULL, 'runtime_default', 'runtime_default', 'd296d7b87a7852dcaaac893a06c7d22fe55ee1bd14f120f5dd7581770df6a282', 'new', '2026-03-01T10:05:00.000005+00:00');
INSERT INTO "assistant_session_choices" ("session_id", "version", "runtime", "provider", "requested_model", "requested_effort", "model_basis", "effort_basis", "route_digest", "binding_basis", "created_at_utc") VALUES (6, 1, 'api_key', 'openai', 'gpt-4o-mini', NULL, 'explicit', 'not_supported', '1fb87a921cf9e8ec2e5ddbfb71385037c87afa4192a09abad6157ce4b0478064', 'new', '2026-03-01T10:42:00.000006+00:00');
INSERT INTO "assistant_session_choices" ("session_id", "version", "runtime", "provider", "requested_model", "requested_effort", "model_basis", "effort_basis", "route_digest", "binding_basis", "created_at_utc") VALUES (7, 1, 'claude_cli', 'claude_code', 'claude-sonnet-4-5', 'max', 'explicit', 'explicit', 'd296d7b87a7852dcaaac893a06c7d22fe55ee1bd14f120f5dd7581770df6a282', 'legacy_confirmed', '2026-03-01T11:19:00.000007+00:00');
INSERT INTO "assistant_session_choices" ("session_id", "version", "runtime", "provider", "requested_model", "requested_effort", "model_basis", "effort_basis", "route_digest", "binding_basis", "created_at_utc") VALUES (8, 1, 'claude_cli', 'claude_code', 'claude-opus-4-1', 'medium', 'explicit', 'explicit', 'd296d7b87a7852dcaaac893a06c7d22fe55ee1bd14f120f5dd7581770df6a282', 'new', '2026-03-01T11:56:00.000008+00:00');
INSERT INTO "assistant_session_choices" ("session_id", "version", "runtime", "provider", "requested_model", "requested_effort", "model_basis", "effort_basis", "route_digest", "binding_basis", "created_at_utc") VALUES (9, 1, 'claude_cli', 'claude_code', 'claude-opus-4-1', 'high', 'explicit', 'explicit', 'd296d7b87a7852dcaaac893a06c7d22fe55ee1bd14f120f5dd7581770df6a282', 'new', '2026-03-01T12:33:00.000009+00:00');
INSERT INTO "assistant_session_choices" ("session_id", "version", "runtime", "provider", "requested_model", "requested_effort", "model_basis", "effort_basis", "route_digest", "binding_basis", "created_at_utc") VALUES (10, 1, 'claude_cli', 'claude_code', 'claude-opus-4-1', 'xhigh', 'explicit', 'explicit', 'd296d7b87a7852dcaaac893a06c7d22fe55ee1bd14f120f5dd7581770df6a282', 'new', '2026-03-01T13:10:00.000010+00:00');

-- assistant_turn_choices: 6 row(s)
INSERT INTO "assistant_turn_choices" ("user_message_id", "assistant_message_id", "version", "requested_json", "reported_json", "created_at_utc") VALUES (4, 5, 1, '{"version": 1, "runtime": "claude_cli", "provider": "claude_code", "requested_model": "claude-opus-4-1", "requested_effort": "low", "model_basis": "explicit", "effort_basis": "explicit", "binding_basis": "new"}', '[]', '2026-03-01T09:28:00.000004+00:00');
INSERT INTO "assistant_turn_choices" ("user_message_id", "assistant_message_id", "version", "requested_json", "reported_json", "created_at_utc") VALUES (6, NULL, 1, '{"version": 1, "runtime": "claude_cli", "provider": "claude_code", "requested_model": "claude-opus-4-1", "requested_effort": "low", "model_basis": "explicit", "effort_basis": "explicit", "binding_basis": "new"}', '[]', '2026-03-01T10:42:00.000006+00:00');
INSERT INTO "assistant_turn_choices" ("user_message_id", "assistant_message_id", "version", "requested_json", "reported_json", "created_at_utc") VALUES (8, NULL, 1, '{"version": 1, "runtime": "claude_cli", "provider": "claude_code", "requested_model": "claude-sonnet-4-5", "requested_effort": "max", "model_basis": "explicit", "effort_basis": "explicit", "binding_basis": "legacy_confirmed"}', '[]', '2026-03-01T11:56:00.000008+00:00');
INSERT INTO "assistant_turn_choices" ("user_message_id", "assistant_message_id", "version", "requested_json", "reported_json", "created_at_utc") VALUES (9, NULL, 1, '{"version": 1, "runtime": "claude_cli", "provider": "claude_code", "requested_model": "claude-opus-4-1", "requested_effort": "medium", "model_basis": "explicit", "effort_basis": "explicit", "binding_basis": "new"}', '[]', '2026-03-01T12:33:00.000009+00:00');
INSERT INTO "assistant_turn_choices" ("user_message_id", "assistant_message_id", "version", "requested_json", "reported_json", "created_at_utc") VALUES (10, NULL, 1, '{"version": 1, "runtime": "claude_cli", "provider": "claude_code", "requested_model": "claude-opus-4-1", "requested_effort": "high", "model_basis": "explicit", "effort_basis": "explicit", "binding_basis": "new"}', '[]', '2026-03-01T13:10:00.000010+00:00');
INSERT INTO "assistant_turn_choices" ("user_message_id", "assistant_message_id", "version", "requested_json", "reported_json", "created_at_utc") VALUES (11, NULL, 1, '{"version": 1, "runtime": "claude_cli", "provider": "claude_code", "requested_model": "claude-opus-4-1", "requested_effort": "xhigh", "model_basis": "explicit", "effort_basis": "explicit", "binding_basis": "new"}', '[]', '2026-03-01T13:47:00.000011+00:00');

-- library_vault: 1 row(s)
INSERT INTO "library_vault" ("singleton", "vault_id", "root_path", "created_at_utc") VALUES (1, '00000000-0000-4000-8001-000000000012', '/does/not/exist/library/resmon-library-00000000-0000-4000-8001-000000000012', '2026-03-01T07:37:00.000001+00:00');

-- library_files: 3 row(s)
INSERT INTO "library_files" ("id", "file_id", "version_id", "vault_id", "sha256", "byte_size", "media_type", "original_name", "relative_path", "created_at_utc") VALUES (1, '00000000-0000-4000-8001-000000000035', '00000000-0000-4000-8001-000000000036', '00000000-0000-4000-8001-000000000012', '6e6e6bc9c7a6612b06336a092c451e9431ebf974967034f99b53d59d90bca6a1', 48, 'text/plain', 'turbulence-notes.txt', 'files/00000000-0000-4000-8001-000000000035/00000000-0000-4000-8001-000000000036.txt', '2026-03-01T07:37:00.000001+00:00');
INSERT INTO "library_files" ("id", "file_id", "version_id", "vault_id", "sha256", "byte_size", "media_type", "original_name", "relative_path", "created_at_utc") VALUES (2, '00000000-0000-4000-8001-000000000043', '00000000-0000-4000-8001-000000000044', '00000000-0000-4000-8001-000000000012', 'd0c4ae9fdedaec0022de77932c9594984d16c8b27ec8fce4a4da7300e72bb6cb', 67, 'text/markdown', 'axion-summary.md', 'files/00000000-0000-4000-8001-000000000043/00000000-0000-4000-8001-000000000044.md', '2026-03-01T08:14:00.000002+00:00');
INSERT INTO "library_files" ("id", "file_id", "version_id", "vault_id", "sha256", "byte_size", "media_type", "original_name", "relative_path", "created_at_utc") VALUES (3, '00000000-0000-4000-8001-000000000038', '00000000-0000-4000-8001-000000000039', '00000000-0000-4000-8001-000000000012', '0f5cf5e575c2968ea8066d53dd79837ac59494e96fb2ad746fafe1b2dc807d95', 59, 'application/pdf', 'supporting-data.pdf', 'files/00000000-0000-4000-8001-000000000038/00000000-0000-4000-8001-000000000039.pdf', '2026-03-01T08:51:00.000003+00:00');

-- library_file_documents: 3 row(s)
INSERT INTO "library_file_documents" ("file_id", "document_id", "linked_at_utc") VALUES ('00000000-0000-4000-8001-000000000035', 1, '2026-03-01T07:37:00.000001+00:00');
INSERT INTO "library_file_documents" ("file_id", "document_id", "linked_at_utc") VALUES ('00000000-0000-4000-8001-000000000043', 10, '2026-03-01T08:14:00.000002+00:00');
INSERT INTO "library_file_documents" ("file_id", "document_id", "linked_at_utc") VALUES ('00000000-0000-4000-8001-000000000043', 4, '2026-03-01T08:51:00.000003+00:00');

-- evidence_projects: 2 row(s)
INSERT INTO "evidence_projects" ("id", "project_id", "vault_id", "name", "revision", "created_at_utc", "updated_at_utc") VALUES (1, '00000000-0000-4000-8001-000000000013', '00000000-0000-4000-8001-000000000012', 'Turbulence closures', 5, '2026-03-01T07:37:00.000001+00:00', '2026-03-01T07:37:00.000001+00:00');
INSERT INTO "evidence_projects" ("id", "project_id", "vault_id", "name", "revision", "created_at_utc", "updated_at_utc") VALUES (2, '00000000-0000-4000-8001-000000000040', '00000000-0000-4000-8001-000000000012', '空のプロジェクト', 1, '2026-03-01T08:14:00.000002+00:00', '2026-03-01T08:14:00.000002+00:00');

-- evidence_project_files: 2 row(s)
INSERT INTO "evidence_project_files" ("id", "project_id", "file_id", "version_id", "added_at_utc") VALUES (1, '00000000-0000-4000-8001-000000000013', '00000000-0000-4000-8001-000000000035', '00000000-0000-4000-8001-000000000036', '2026-03-01T07:37:00.000001+00:00');
INSERT INTO "evidence_project_files" ("id", "project_id", "file_id", "version_id", "added_at_utc") VALUES (2, '00000000-0000-4000-8001-000000000013', '00000000-0000-4000-8001-000000000038', '00000000-0000-4000-8001-000000000039', '2026-03-01T08:14:00.000002+00:00');

-- evidence_notes: 2 row(s)
INSERT INTO "evidence_notes" ("id", "note_id", "project_id", "file_id", "version_id", "kind", "body", "page_number", "extraction_contract", "page_text_sha256", "start_codepoint", "end_codepoint", "quote", "revision", "created_at_utc", "updated_at_utc") VALUES (1, '00000000-0000-4000-8001-000000000034', '00000000-0000-4000-8001-000000000013', '00000000-0000-4000-8001-000000000035', '00000000-0000-4000-8001-000000000036', 'note', 'Compare with the 2021 closure paper — 要確認。', NULL, NULL, NULL, NULL, NULL, NULL, 1, '2026-03-01T07:37:00.000001+00:00', '2026-03-01T07:37:00.000001+00:00');
INSERT INTO "evidence_notes" ("id", "note_id", "project_id", "file_id", "version_id", "kind", "body", "page_number", "extraction_contract", "page_text_sha256", "start_codepoint", "end_codepoint", "quote", "revision", "created_at_utc", "updated_at_utc") VALUES (2, '00000000-0000-4000-8001-000000000037', '00000000-0000-4000-8001-000000000013', '00000000-0000-4000-8001-000000000035', '00000000-0000-4000-8001-000000000036', 'passage', '', 1, 'library-text-lf/v1', '6e6e6bc9c7a6612b06336a092c451e9431ebf974967034f99b53d59d90bca6a1', 17, 36, 'turbulence closures', 1, '2026-03-01T08:14:00.000002+00:00', '2026-03-01T08:14:00.000002+00:00');

-- evidence_answers: 7 row(s)
INSERT INTO "evidence_answers" ("id", "answer_id", "preview_id", "vault_id", "project_id", "project_revision", "mode", "state", "request_json", "request_sha256", "private_binding_json", "private_native_session_id", "owner_runtime_id", "partial_text", "result_json", "reports_json", "usage_json", "error_code", "error_message", "cleanup_state", "created_at_utc", "started_at_utc", "finished_at_utc") VALUES (1, '00000000-0000-4000-8001-000000000010', '00000000-0000-4000-8001-000000000011', '00000000-0000-4000-8001-000000000012', '00000000-0000-4000-8001-000000000013', 5, 'question', 'admitted', '{"mode":"question","question":"What do these notes establish?","selection":{"note_ids":[0]},"version":1}', '5f8a638ca3b4dfa9e82d48b523b4c1b02529b2085296603b53afa3ee0375be83', '{"provider":"claude_code","requested_model":"claude-opus-4-1","runtime":"claude_cli","version":1}', '00000000-0000-4000-8001-000000000014', '00000000-0000-4000-8001-000000000015', '', NULL, '[]', NULL, NULL, NULL, 'not_started', '2026-03-01T07:37:00.000001+00:00', NULL, NULL);
INSERT INTO "evidence_answers" ("id", "answer_id", "preview_id", "vault_id", "project_id", "project_revision", "mode", "state", "request_json", "request_sha256", "private_binding_json", "private_native_session_id", "owner_runtime_id", "partial_text", "result_json", "reports_json", "usage_json", "error_code", "error_message", "cleanup_state", "created_at_utc", "started_at_utc", "finished_at_utc") VALUES (2, '00000000-0000-4000-8001-000000000016', '00000000-0000-4000-8001-000000000017', '00000000-0000-4000-8001-000000000012', '00000000-0000-4000-8001-000000000013', 5, 'briefing', 'running', '{"mode":"briefing","question":"What do these notes establish?","selection":{"note_ids":[1]},"version":1}', 'c2edad80d8f29f7e14025beeac1bc0c4fa379c7d033af9970b5f86d72088766b', '{"provider":"claude_code","requested_model":"claude-opus-4-1","runtime":"claude_cli","version":1}', '00000000-0000-4000-8001-000000000018', '00000000-0000-4000-8001-000000000015', 'Working through the first note', NULL, '[{"model":"claude-opus-4-1","source":"claude_system_init_model"}]', NULL, NULL, NULL, 'pending', '2026-03-01T08:14:00.000002+00:00', '2026-03-01T08:14:00.000002+00:00', NULL);
INSERT INTO "evidence_answers" ("id", "answer_id", "preview_id", "vault_id", "project_id", "project_revision", "mode", "state", "request_json", "request_sha256", "private_binding_json", "private_native_session_id", "owner_runtime_id", "partial_text", "result_json", "reports_json", "usage_json", "error_code", "error_message", "cleanup_state", "created_at_utc", "started_at_utc", "finished_at_utc") VALUES (3, '00000000-0000-4000-8001-000000000019', '00000000-0000-4000-8001-000000000020', '00000000-0000-4000-8001-000000000012', '00000000-0000-4000-8001-000000000013', 5, 'question', 'succeeded', '{"mode":"question","question":"What do these notes establish?","selection":{"note_ids":[2]},"version":1}', 'e8b3fb2930fce118860cc1d2277ece3fc33690dd8584904f4b7cac13d9d2f823', '{"provider":"claude_code","requested_model":"claude-opus-4-1","runtime":"claude_cli","version":1}', '00000000-0000-4000-8001-000000000021', '00000000-0000-4000-8001-000000000015', '', '{"citations":[{"note_index":2}],"text":"Both notes point at the same 2021 result."}', '[{"model":"claude-opus-4-1","source":"claude_system_init_model"}]', '{"input_tokens":902,"output_tokens":120}', NULL, NULL, 'confirmed', '2026-03-01T08:51:00.000003+00:00', '2026-03-01T08:51:00.000003+00:00', '2026-03-01T08:51:00.000003+00:00');
INSERT INTO "evidence_answers" ("id", "answer_id", "preview_id", "vault_id", "project_id", "project_revision", "mode", "state", "request_json", "request_sha256", "private_binding_json", "private_native_session_id", "owner_runtime_id", "partial_text", "result_json", "reports_json", "usage_json", "error_code", "error_message", "cleanup_state", "created_at_utc", "started_at_utc", "finished_at_utc") VALUES (4, '00000000-0000-4000-8001-000000000022', '00000000-0000-4000-8001-000000000023', '00000000-0000-4000-8001-000000000012', '00000000-0000-4000-8001-000000000013', 5, 'briefing', 'refused', '{"mode":"briefing","question":"What do these notes establish?","selection":{"note_ids":[3]},"version":1}', 'a44f43ed7bdd11eb719dc904476eefbd9346f1aa97b6bf2eb9b0bbf278c57c04', '{"provider":"claude_code","requested_model":"claude-opus-4-1","runtime":"claude_cli","version":1}', '00000000-0000-4000-8001-000000000024', '00000000-0000-4000-8001-000000000015', '', '{"citations":[{"note_index":3}],"text":"Both notes point at the same 2021 result."}', '[{"model":"claude-opus-4-1","source":"claude_system_init_model"}]', '{"input_tokens":903,"output_tokens":120}', NULL, NULL, 'confirmed', '2026-03-01T09:28:00.000004+00:00', '2026-03-01T09:28:00.000004+00:00', '2026-03-01T09:28:00.000004+00:00');
INSERT INTO "evidence_answers" ("id", "answer_id", "preview_id", "vault_id", "project_id", "project_revision", "mode", "state", "request_json", "request_sha256", "private_binding_json", "private_native_session_id", "owner_runtime_id", "partial_text", "result_json", "reports_json", "usage_json", "error_code", "error_message", "cleanup_state", "created_at_utc", "started_at_utc", "finished_at_utc") VALUES (5, '00000000-0000-4000-8001-000000000025', '00000000-0000-4000-8001-000000000026', '00000000-0000-4000-8001-000000000012', '00000000-0000-4000-8001-000000000013', 5, 'question', 'failed', '{"mode":"question","question":"What do these notes establish?","selection":{"note_ids":[4]},"version":1}', '366b924946476787b0fed52c162e475d66e74611d721b7819c7e56673195d50d', '{"provider":"claude_code","requested_model":"claude-opus-4-1","runtime":"claude_cli","version":1}', '00000000-0000-4000-8001-000000000027', '00000000-0000-4000-8001-000000000015', '', NULL, '[{"model":"claude-opus-4-1","source":"claude_system_init_model"}]', NULL, 'runtime_error', 'The assistant process exited before answering.', 'unknown', '2026-03-01T10:05:00.000005+00:00', '2026-03-01T10:05:00.000005+00:00', '2026-03-01T10:05:00.000005+00:00');
INSERT INTO "evidence_answers" ("id", "answer_id", "preview_id", "vault_id", "project_id", "project_revision", "mode", "state", "request_json", "request_sha256", "private_binding_json", "private_native_session_id", "owner_runtime_id", "partial_text", "result_json", "reports_json", "usage_json", "error_code", "error_message", "cleanup_state", "created_at_utc", "started_at_utc", "finished_at_utc") VALUES (6, '00000000-0000-4000-8001-000000000028', '00000000-0000-4000-8001-000000000029', '00000000-0000-4000-8001-000000000012', '00000000-0000-4000-8001-000000000013', 5, 'briefing', 'cancelled', '{"mode":"briefing","question":"What do these notes establish?","selection":{"note_ids":[5]},"version":1}', '662e60690130108e6cc5556ebf872d8811c3679b44a1dc968c3529813ae12029', '{"provider":"claude_code","requested_model":"claude-opus-4-1","runtime":"claude_cli","version":1}', '00000000-0000-4000-8001-000000000030', '00000000-0000-4000-8001-000000000015', 'Partial text kept from the cancelled run', NULL, '[{"model":"claude-opus-4-1","source":"claude_system_init_model"}]', NULL, NULL, NULL, 'confirmed', '2026-03-01T10:42:00.000006+00:00', '2026-03-01T10:42:00.000006+00:00', '2026-03-01T10:42:00.000006+00:00');
INSERT INTO "evidence_answers" ("id", "answer_id", "preview_id", "vault_id", "project_id", "project_revision", "mode", "state", "request_json", "request_sha256", "private_binding_json", "private_native_session_id", "owner_runtime_id", "partial_text", "result_json", "reports_json", "usage_json", "error_code", "error_message", "cleanup_state", "created_at_utc", "started_at_utc", "finished_at_utc") VALUES (7, '00000000-0000-4000-8001-000000000031', '00000000-0000-4000-8001-000000000032', '00000000-0000-4000-8001-000000000012', '00000000-0000-4000-8001-000000000013', 5, 'question', 'interrupted', '{"mode":"question","question":"What do these notes establish?","selection":{"note_ids":[6]},"version":1}', '048e12248e707756e807d96d038ab6ca8aa4f137449c121c51453de943c55fb2', '{"provider":"claude_code","requested_model":"claude-opus-4-1","runtime":"claude_cli","version":1}', '00000000-0000-4000-8001-000000000033', '00000000-0000-4000-8001-000000000015', '', NULL, '[{"model":"claude-opus-4-1","source":"claude_system_init_model"}]', NULL, 'interrupted', 'resmon closed while the answer was streaming.', 'unknown', '2026-03-01T11:19:00.000007+00:00', '2026-03-01T11:19:00.000007+00:00', '2026-03-01T11:19:00.000007+00:00');

-- executions: 9 row(s)
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "owner_pid", "owner_runtime_id", "last_seen_at_utc", "interrupted_reason", "restarted_from", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source", "request_id") VALUES (1, 'deep_dive', 1, 1, '{"keywords": "diffusion", "index": 0}', '2026-02-01T06:00:00', '2026-02-01T06:12:00', 'completed', 12, 3, '/does/not/exist/run-0.log', '/does/not/exist/run-0.json', NULL, '[{"stage": "search", "source": "arxiv", "count": 9}, {"stage": "search", "source": "openalex", "count": 3}, {"stage": "dedup", "removed": 1}]', NULL, 10007, '00000000-0000-4000-8001-000000000041', '2026-03-01T07:37:00.000001+00:00', NULL, NULL, NULL, 12, 9, 2, 1, 1, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "owner_pid", "owner_runtime_id", "last_seen_at_utc", "interrupted_reason", "restarted_from", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source", "request_id") VALUES (2, 'deep_sweep', NULL, 2, '{"keywords": "diffusion", "index": 1}', '2026-02-02T06:00:00', '2026-02-02T06:12:00', 'failed', 13, 4, '/does/not/exist/run-1.log', '/does/not/exist/run-1.json', 'Upstream returned HTTP 503', NULL, NULL, 10014, '00000000-0000-4000-8001-000000000041', '2026-03-01T08:14:00.000002+00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "owner_pid", "owner_runtime_id", "last_seen_at_utc", "interrupted_reason", "restarted_from", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source", "request_id") VALUES (3, 'automated_sweep', 2, NULL, '{"keywords": "diffusion", "index": 2}', '2026-02-03T06:00:00', '2026-02-03T06:12:00', 'completed', 14, 5, '/does/not/exist/run-2.log', '/does/not/exist/run-2.json', NULL, NULL, NULL, 10021, '00000000-0000-4000-8001-000000000041', '2026-03-01T08:51:00.000003+00:00', NULL, NULL, NULL, 7, 7, 0, 0, NULL, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "owner_pid", "owner_runtime_id", "last_seen_at_utc", "interrupted_reason", "restarted_from", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source", "request_id") VALUES (4, 'deep_dive', NULL, NULL, '{"keywords": "diffusion", "index": 3}', '2026-02-04T06:00:00', '2026-02-04T06:12:00', 'cancelled', 15, 6, '/does/not/exist/run-3.log', '/does/not/exist/run-3.json', NULL, NULL, NULL, 10028, '00000000-0000-4000-8001-000000000041', '2026-03-01T09:28:00.000004+00:00', NULL, NULL, 'user cancelled from the Dashboard', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "owner_pid", "owner_runtime_id", "last_seen_at_utc", "interrupted_reason", "restarted_from", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source", "request_id") VALUES (5, 'deep_sweep', NULL, NULL, '{"keywords": "diffusion", "index": 4}', '2026-02-05T06:00:00', NULL, 'running', 0, 0, NULL, NULL, NULL, NULL, 'querying sources', 10035, '00000000-0000-4000-8001-000000000041', '2026-03-01T10:05:00.000005+00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "owner_pid", "owner_runtime_id", "last_seen_at_utc", "interrupted_reason", "restarted_from", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source", "request_id") VALUES (6, 'automated_sweep', 2, NULL, '{"keywords": "retraction", "reason": "owner_dead"}', '2026-02-10T04:00:00', '2026-02-10T04:05:00', 'interrupted', 0, 0, NULL, NULL, NULL, NULL, NULL, 10042, '00000000-0000-4000-8001-000000000041', '2026-03-01T10:42:00.000006+00:00', 'owner_dead', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "owner_pid", "owner_runtime_id", "last_seen_at_utc", "interrupted_reason", "restarted_from", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source", "request_id") VALUES (7, 'automated_sweep', 2, NULL, '{"keywords": "retraction", "reason": "daemon_restart"}', '2026-02-11T04:00:00', '2026-02-11T04:05:00', 'interrupted', 0, 0, NULL, NULL, NULL, NULL, NULL, 10049, '00000000-0000-4000-8001-000000000041', '2026-03-01T11:19:00.000007+00:00', 'daemon_restart', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "owner_pid", "owner_runtime_id", "last_seen_at_utc", "interrupted_reason", "restarted_from", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source", "request_id") VALUES (8, 'automated_sweep', 2, NULL, '{"keywords": "retraction", "reason": "unknown"}', '2026-02-12T04:00:00', '2026-02-12T04:05:00', 'interrupted', 0, 0, NULL, NULL, NULL, NULL, NULL, 10056, '00000000-0000-4000-8001-000000000041', '2026-03-01T11:56:00.000008+00:00', 'unknown', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "executions" ("id", "execution_type", "routine_id", "saved_configuration_id", "parameters", "start_time", "end_time", "status", "result_count", "new_result_count", "log_path", "result_path", "error_message", "progress_events", "current_stage", "owner_pid", "owner_runtime_id", "last_seen_at_utc", "interrupted_reason", "restarted_from", "cancel_reason", "dedup_total", "dedup_new", "dedup_duplicates", "dedup_invalid", "dedup_cross_source", "request_id") VALUES (9, 'automated_sweep', 2, NULL, '{"keywords": "retraction", "restart": true}', '2026-02-13T04:30:00', '2026-02-13T04:41:00', 'completed', 4, 1, NULL, NULL, NULL, NULL, NULL, 10063, '00000000-0000-4000-8001-000000000041', '2026-03-01T12:33:00.000009+00:00', NULL, 6, NULL, NULL, NULL, NULL, NULL, NULL, '00000000-0000-4000-8001-000000000042');

-- routine_missed_fires: 3 row(s)
INSERT INTO "routine_missed_fires" ("id", "routine_id", "due_at_utc", "observed_at_utc", "disposition") VALUES (1, 1, '2026-03-01T07:37:00.000001+00:00', '2026-03-01T07:37:00.000001+00:00', 'ran_late');
INSERT INTO "routine_missed_fires" ("id", "routine_id", "due_at_utc", "observed_at_utc", "disposition") VALUES (2, 1, '2026-03-01T08:14:00.000002+00:00', '2026-03-01T08:14:00.000002+00:00', 'ran_late');
INSERT INTO "routine_missed_fires" ("id", "routine_id", "due_at_utc", "observed_at_utc", "disposition") VALUES (3, 2, '2026-03-01T08:51:00.000003+00:00', '2026-03-01T08:51:00.000003+00:00', 'recorded');

-- routine_delivery_targets: 7 row(s)
INSERT INTO "routine_delivery_targets" ("id", "routine_id", "channel", "target", "enabled", "mode", "created_at_utc", "updated_at_utc") VALUES (1, 1, 'email', '', 1, 'automatic', '2026-03-01T07:37:00.000001+00:00', '2026-03-01T07:37:00.000001+00:00');
INSERT INTO "routine_delivery_targets" ("id", "routine_id", "channel", "target", "enabled", "mode", "created_at_utc", "updated_at_utc") VALUES (2, 1, 'folder', '/does/not/exist/reports', 1, 'automatic', '2026-03-01T08:14:00.000002+00:00', '2026-03-01T08:14:00.000002+00:00');
INSERT INTO "routine_delivery_targets" ("id", "routine_id", "channel", "target", "enabled", "mode", "created_at_utc", "updated_at_utc") VALUES (3, 1, 'webhook', 'https://example.org/resmon-receiver', 1, 'review', '2026-03-01T08:51:00.000003+00:00', '2026-03-01T08:51:00.000003+00:00');
INSERT INTO "routine_delivery_targets" ("id", "routine_id", "channel", "target", "enabled", "mode", "created_at_utc", "updated_at_utc") VALUES (4, 1, 'feed', '/does/not/exist/feeds', 0, 'automatic', '2026-03-01T09:28:00.000004+00:00', '2026-03-01T09:28:00.000004+00:00');
INSERT INTO "routine_delivery_targets" ("id", "routine_id", "channel", "target", "enabled", "mode", "created_at_utc", "updated_at_utc") VALUES (5, 2, 'feed', '/does/not/exist/feeds/retractions', 1, 'automatic', '2026-03-01T10:05:00.000005+00:00', '2026-03-01T10:05:00.000005+00:00');
INSERT INTO "routine_delivery_targets" ("id", "routine_id", "channel", "target", "enabled", "mode", "created_at_utc", "updated_at_utc") VALUES (6, 2, 'folder', '/does/not/exist/reports/retractions', 1, 'review', '2026-03-01T10:42:00.000006+00:00', '2026-03-01T10:42:00.000006+00:00');
INSERT INTO "routine_delivery_targets" ("id", "routine_id", "channel", "target", "enabled", "mode", "created_at_utc", "updated_at_utc") VALUES (7, 2, 'webhook', 'http://127.0.0.1:9099/hook', 1, 'automatic', '2026-03-01T11:19:00.000007+00:00', '2026-03-01T11:19:00.000007+00:00');

-- deliveries: 6 row(s)
INSERT INTO "deliveries" ("id", "execution_id", "target_id", "channel", "target_snapshot", "state", "attempts", "next_attempt_at_utc", "last_error", "artifact_sha256", "owner_pid", "owner_runtime_id", "queued_at_utc", "delivered_at_utc") VALUES (1, 1, 1, 'email', '', 'delivered', 1, NULL, NULL, 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', NULL, NULL, '2026-03-01T07:37:00.000001+00:00', '2026-03-01T07:37:00.000001+00:00');
INSERT INTO "deliveries" ("id", "execution_id", "target_id", "channel", "target_snapshot", "state", "attempts", "next_attempt_at_utc", "last_error", "artifact_sha256", "owner_pid", "owner_runtime_id", "queued_at_utc", "delivered_at_utc") VALUES (2, 1, 2, 'folder', '/does/not/exist/reports', 'failed', 1, '2026-03-01T08:14:00.000002+00:00', 'The destination folder is not mounted.', NULL, NULL, NULL, '2026-03-01T08:14:00.000002+00:00', NULL);
INSERT INTO "deliveries" ("id", "execution_id", "target_id", "channel", "target_snapshot", "state", "attempts", "next_attempt_at_utc", "last_error", "artifact_sha256", "owner_pid", "owner_runtime_id", "queued_at_utc", "delivered_at_utc") VALUES (3, 1, 3, 'webhook', 'https://example.org/resmon-receiver', 'awaiting_review', 0, NULL, NULL, NULL, NULL, NULL, '2026-03-01T08:51:00.000003+00:00', NULL);
INSERT INTO "deliveries" ("id", "execution_id", "target_id", "channel", "target_snapshot", "state", "attempts", "next_attempt_at_utc", "last_error", "artifact_sha256", "owner_pid", "owner_runtime_id", "queued_at_utc", "delivered_at_utc") VALUES (4, 3, 5, 'feed', '/does/not/exist/feeds/retractions', 'delivering', 1, NULL, NULL, NULL, 10028, '00000000-0000-4000-8001-000000000009', '2026-03-01T09:28:00.000004+00:00', NULL);
INSERT INTO "deliveries" ("id", "execution_id", "target_id", "channel", "target_snapshot", "state", "attempts", "next_attempt_at_utc", "last_error", "artifact_sha256", "owner_pid", "owner_runtime_id", "queued_at_utc", "delivered_at_utc") VALUES (5, 3, 6, 'folder', '/does/not/exist/reports/retractions', 'skipped', 0, NULL, NULL, NULL, NULL, NULL, '2026-03-01T10:05:00.000005+00:00', NULL);
INSERT INTO "deliveries" ("id", "execution_id", "target_id", "channel", "target_snapshot", "state", "attempts", "next_attempt_at_utc", "last_error", "artifact_sha256", "owner_pid", "owner_runtime_id", "queued_at_utc", "delivered_at_utc") VALUES (6, 3, 7, 'webhook', 'http://127.0.0.1:9099/hook', 'queued', 0, NULL, NULL, NULL, NULL, NULL, '2026-03-01T10:42:00.000006+00:00', NULL);

-- AUTOINCREMENT high-water marks. Restored explicitly because
-- a deleted row leaves the sequence above the highest surviving id.
UPDATE sqlite_sequence SET seq = 11 WHERE name = 'assistant_messages';
UPDATE sqlite_sequence SET seq = 10 WHERE name = 'assistant_sessions';
UPDATE sqlite_sequence SET seq = 3 WHERE name = 'cloud_sync';
UPDATE sqlite_sequence SET seq = 6 WHERE name = 'deliveries';
UPDATE sqlite_sequence SET seq = 13 WHERE name = 'documents';
UPDATE sqlite_sequence SET seq = 7 WHERE name = 'evidence_answers';
UPDATE sqlite_sequence SET seq = 2 WHERE name = 'evidence_notes';
UPDATE sqlite_sequence SET seq = 2 WHERE name = 'evidence_project_files';
UPDATE sqlite_sequence SET seq = 2 WHERE name = 'evidence_projects';
UPDATE sqlite_sequence SET seq = 10 WHERE name = 'executions';
UPDATE sqlite_sequence SET seq = 3 WHERE name = 'library_files';
UPDATE sqlite_sequence SET seq = 7 WHERE name = 'routine_delivery_targets';
UPDATE sqlite_sequence SET seq = 3 WHERE name = 'routine_missed_fires';
UPDATE sqlite_sequence SET seq = 3 WHERE name = 'routines';
UPDATE sqlite_sequence SET seq = 3 WHERE name = 'saved_configurations';
UPDATE sqlite_sequence SET seq = 4 WHERE name = 'watch_profiles';

COMMIT;
