/** Authored local evidence, real Electron/backend/HTTP/SSE, synthetic CLI/API.
 * Scripted native chooser/download destinations are not physical-device proof. */
import {test,expect,_electron,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'fs';import os from 'os';import path from 'path';import {execFileSync} from 'child_process';import {createHash} from 'crypto';
import {FRONTEND_ROOT,REPO_ROOT,launchEnv,ensureScreenshotDir,selectedEvidenceTransport} from './fixtures/resmon-app';
import {LibraryFile,LibraryStatus,LibraryPage} from '../src/api/library';import {Project,SavedNote} from '../src/api/evidence';// Wire assertions below deliberately avoid importing renderer TSX into the e2e compiler.
interface Answer {answer_id:string;request_sha256:string;state:string;cleanup_state:string;request:{user_prompt:string;system_text:string;payload:{sources:unknown[];notes:unknown[];coverage:{files:{known_page_count:number|null;unexamined_page_count:number|null}[]};requested:{requested_model:string|null}}};reports:{model:string}[];usage:unknown;result:{sections:{items:{citations:{quote:string}[]}[]}[]}|null;partial_text:string}
interface BrowserReceipt {url:string;method:string;status:number;body:string}
interface Preview {request:Answer['request'];request_sha256:string}
const hash=(raw:Buffer|string)=>createHash('sha256').update(raw).digest('hex');const alive=(pid:number)=>{try{process.kill(pid,0);return true;}catch{return false;}};
const started=(pid:number)=>execFileSync('ps',['-p',String(pid),'-o','lstart='],{encoding:'utf8'}).trim();
for(const mode of ['question','briefing'] as const)test(`Selected evidence ${mode}: actual consent, ${mode==='question'?'CLI':'API'} citations, Stop, history, restart and ZIP`,async()=>{
 test.setTimeout(360_000);
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),`resmon-selected-${mode}-`))),state=path.join(root,'state'),profile=path.join(root,'profile'),originals=path.join(root,'originals'),parent=path.join(root,'vault-parent'),exports=path.join(root,'exports');for(const dir of [state,profile,originals,parent,exports])fs.mkdirSync(dir);
 const env=launchEnv(state,true);env.PYTHON_KEYRING_BACKEND='keyring.backends.null.Keyring';
 // CI supplies a PATH name; native script shebangs require the resolved interpreter.
 const requestedPython=env.RESMON_PYTHON,python=execFileSync(requestedPython,['-c','import sys;print(sys.executable)'],{env,encoding:'utf8'}).trim();expect(path.isAbsolute(python)).toBe(true);
 const fake=await selectedEvidenceTransport(root,python);env.RESMON_PYTHON=fake.backend;
 const out=ensureScreenshotDir(),receipt=(name:string,value:unknown)=>fs.writeFileSync(path.join(out,`selected-${mode}-${name}.json`),JSON.stringify(value,null,2));receipt('fixture',{...fake.receipt(),requestedPython,resolvedPython:python});
 const py=(code:string,...args:string[])=>execFileSync(python,['-c',code,...args],{cwd:REPO_ROOT,env,encoding:'utf8'});
 const names=['two-pages.pdf','unicode.txt','hostile.md'];for(const name of names)fs.copyFileSync(path.join(REPO_ROOT,'resmon_scripts/verification_scripts/fixtures/evidence',name),path.join(originals,name));const originalHashes=Object.fromEntries(names.map(n=>[n,hash(fs.readFileSync(path.join(originals,n)))]));
 let app:ElectronApplication|undefined,win!:Page,base='',origin='',vid='',pid='',vaultRoot='';const backends:number[]=[],instances:unknown[]=[],errors:string[]=[],transportFailures:unknown[]=[],responses:unknown[]=[],saved:Answer[]=[];let catalog:LibraryFile[]=[];
 const req=async<T>(url:string,method='GET',body?:unknown):Promise<T>=>{const r=await fetch(base+url,{method,headers:{Origin:origin,'X-Resmon-Library':'1',...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});expect(r.ok,await r.clone().text()).toBe(true);return r.json() as Promise<T>;};
 const answers=async()=>await req<{answers:{answer_id:string}[];total:number}>(`/api/evidence/projects/${pid}/answers?expected_vault_id=${vid}`);
 const detail=async(id:string)=>await req<Answer>(`/api/evidence/projects/${pid}/answers/${id}?expected_vault_id=${vid}`);
 const sql=()=>py("import sqlite3,json,sys;c=sqlite3.connect(sys.argv[1]);print(json.dumps({t:c.execute('SELECT count(*) FROM '+t).fetchone()[0] for t in ['evidence_answers','assistant_sessions','routines']}));c.close()",env.RESMON_DB_PATH);
 const launch=async()=>{
  app=await _electron.launch({args:['.',`--user-data-dir=${profile}`],cwd:FRONTEND_ROOT,env,timeout:180_000});win=await app.firstWindow();win.on('pageerror',e=>{errors.push(e.stack??e.message);receipt('errors',errors);});win.on('console',m=>{if(m.type()==='error'){transportFailures.push({kind:'console',text:m.text(),location:m.location()});receipt('transport-failures',transportFailures);}});win.on('requestfailed',r=>{transportFailures.push({kind:'requestfailed',url:r.url(),error:r.failure()?.errorText});receipt('transport-failures',transportFailures);});win.on('response',r=>{if(r.request().method()==='POST'&&r.url().endsWith('/answers'))void r.text().then(body=>{responses.push({url:r.url(),status:r.status(),headers:r.headers(),body});receipt('browser-send-responses',responses);}).catch(error=>{responses.push({url:r.url(),readError:String(error)});receipt('browser-send-responses',responses);});});await win.waitForSelector('.app-main');
  const port=await win.evaluate(()=>window.resmonAPI!.getBackendPort());expect(Number(port)).toBeGreaterThan(0);expect(port).not.toBe('8742');base=`http://127.0.0.1:${port}`;origin=new URL(win.url()).origin;const health=await req<{pid:number;identity:{runtime_id:string;schema_version:number}}>('/api/health');expect(health.identity.schema_version).toBe(18);backends.push(health.pid);
  const identity=await app.evaluate(({app})=>({pid:process.pid,state:process.env.RESMON_STATE_DIR,database:process.env.RESMON_DB_PATH,portFile:process.env.RESMON_PORT_FILE,profile:app.getPath('userData')}));expect(identity.state).toBe(state);expect(identity.database).toBe(env.RESMON_DB_PATH);expect(identity.profile).toBe(profile);expect(fs.readFileSync(env.RESMON_PORT_FILE,'utf8').trim()).toBe(port);instances.push({...identity,health,mainStart:started(identity.pid),backendStart:started(health.pid),source:REPO_ROOT,port});receipt('instances',instances);
  await win.evaluate(()=>{const original=window.fetch;const entries:{url:string;method:string;status:number;body:string}[]=[];(window as unknown as {selectedReceipts:typeof entries}).selectedReceipts=entries;window.fetch=async(input,init)=>{const response=await original(input,init);const url=String(input);if(init?.method==='POST'&&/\/(answer-previews|answers)$/.test(url))entries.push({url,method:init.method,status:response.status,body:await response.clone().text()});return response;};});
  await app.evaluate(({session,shell,dialog},args)=>{const g=globalThis as unknown as {selectedNetwork:{allowed:string[];blocked:string[];opens:string[];downloads:string[]}};g.selectedNetwork={allowed:[],blocked:[],opens:[],downloads:[]};session.defaultSession.webRequest.onBeforeRequest({urls:['*://*/*']},(d,cb)=>{const local=d.url.startsWith(args.base+'/')||d.url.startsWith(args.origin+'/');(local?g.selectedNetwork.allowed:g.selectedNetwork.blocked).push(d.url);cb({cancel:!local});});shell.openExternal=async url=>{g.selectedNetwork.opens.push(url);};shell.openPath=async target=>{g.selectedNetwork.opens.push(target);return 'External open blocked in synthetic selected fixture';};dialog.showOpenDialog=async()=>({canceled:false,filePaths:[args.parent]});session.defaultSession.on('will-download',(_e,item)=>g.selectedNetwork.downloads.push(item.getFilename()));},{base,origin,parent});
 };
 const screenshot=async(name:string)=>{await win.screenshot({path:path.join(out,`selected-${mode}-${name}.png`)});const bytes=await app!.evaluate(async({BrowserWindow})=>Array.from((await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG()));fs.writeFileSync(path.join(out,`selected-${mode}-${name}-native.png`),Buffer.from(bytes));};
 const browserReceipts=async()=>win.evaluate(()=>(window as unknown as {selectedReceipts:BrowserReceipt[]}).selectedReceipts);
 const captureStart=async()=> (await browserReceipts()).length;
 const capturedResponse=async(start:number,suffix:string)=>{await expect.poll(async()=>(await browserReceipts()).slice(start).filter(r=>r.url.endsWith(suffix)).length).toBe(1);const all=await browserReceipts();receipt('native-browser-responses',all);return all.slice(start).find(r=>r.url.endsWith(suffix))!;};
 const prepare=async(note=false)=>{
  await win.getByRole('button',{name:'New selected-evidence answer'}).click();const dialog=win.getByRole('dialog',{name:'Select evidence for an answer'});await expect(dialog).toBeVisible();
  await dialog.getByLabel('Physical page for two-pages.pdf').fill('1');await dialog.getByRole('button',{name:'Add two-pages.pdf page',exact:true}).click();
  if(mode==='question'&&await dialog.getByRole('button',{name:'Add current reader passage'}).count())await dialog.getByRole('button',{name:'Add current reader passage'}).click();else await dialog.getByRole('button',{name:'Add unicode.txt logical page 1'}).click();
  if(note)await dialog.getByLabel(/Include note body: SELECTED OWNER NOTE/).check();
  await dialog.getByLabel('Answer format').selectOption(mode);await dialog.getByLabel('Question or briefing instruction').fill('Describe only these explicit selected excerpts. <script>literal instruction</script>');
  await dialog.getByLabel('Connection',{exact:true}).selectOption(mode==='question'?'claude_cli:claude_code':'api_key:custom');await dialog.getByLabel('Model',{exact:true}).fill('requested-synthetic-model');if(mode==='question')await dialog.getByLabel('Effort',{exact:true}).selectOption('high');
  const start=await captureStart();await dialog.getByRole('button',{name:'Preview selected content'}).click();const raw=await capturedResponse(start,'/answer-previews');expect(raw.status,raw.body).toBe(200);const p=JSON.parse(raw.body) as Preview;await expect(dialog.getByRole('heading',{name:'Inspect before Send'})).toBeVisible();return {dialog,preview:p};
 };
 // Hold the actual native fetch Response: CDP fulfill can expose status 0 in
 // Electron when combined with the application's request-header policy.
 const holdResponse=async(target:string,failAfterRelease=false)=>win.evaluate(({target,failAfterRelease})=>{
  const original=window.fetch;const state={ready:false,status:0,body:'',release:()=>{},restore:()=>{window.fetch=original;}};
  (window as unknown as {selectedHeld:typeof state}).selectedHeld=state;
  window.fetch=async(input,init)=>{const response=await original(input,init);if(input===target&&init?.method==='POST'){state.status=response.status;state.body=await response.clone().text();await new Promise<void>(resolve=>{state.release=resolve;state.ready=true;});if(failAfterRelease)throw new Error('RETIRED_PREVIEW_ERROR');}return response;};
 },{target,failAfterRelease});
 const heldResponse=async()=>win.evaluate(()=>{const s=(window as unknown as {selectedHeld:{ready:boolean;status:number;body:string}}).selectedHeld;return {ready:s.ready,status:s.status,body:s.body};});
 const releaseResponse=async()=>win.evaluate(()=>{const s=(window as unknown as {selectedHeld:{restore:()=>void;release:()=>void}}).selectedHeld;s.restore();s.release();});
 const send=async(expected:'succeeded'|'failed'|'refused'='succeeded',note=false)=>{const {dialog,preview}=await prepare(note);const start=await captureStart();await dialog.getByRole('button',{name:'Send selected evidence'}).focus();await win.keyboard.press('Enter');const raw=await capturedResponse(start,'/answers');expect(raw.status,raw.body).toBe(202);const admitted=JSON.parse(raw.body) as Answer;await expect.poll(async()=>(await detail(admitted.answer_id)).cleanup_state).toBe('confirmed');const a=await detail(admitted.answer_id);expect(a.state).toBe(expected);expect(a.request).toEqual(preview.request);await expect(win.getByRole('button',{name:'New selected-evidence answer'})).toBeEnabled();saved.push(a);receipt('saved-answers',saved);return a;};
 const exportAnswer=async(a:Answer,label:string)=>{const target=path.join(exports,label+'.zip');await app!.evaluate(({session},destination)=>session.defaultSession.once('will-download',(_event,download)=>download.setSavePath(destination)),target);await win.getByRole('button',{name:'Export this answer and selected text'}).click();await expect.poll(()=>fs.existsSync(target)&&fs.statSync(target).size>0).toBe(true);const zip=JSON.parse(py("import zipfile,json,sys;z=zipfile.ZipFile(sys.argv[1]);assert z.testzip() is None;print(json.dumps({'names':z.namelist(),'answer':json.loads(z.read('answer.json')),'evidence':json.loads(z.read('evidence.json')),'markdown':z.read('answer.md').decode()}));z.close()",target)) as {names:string[];answer:Answer;evidence:{sources:unknown[]};markdown:string};expect(zip.names.sort()).toEqual(['answer.json','answer.md','evidence.json']);expect(zip.answer.answer_id).toBe(a.answer_id);expect(zip.answer.request_sha256).toBe(a.request_sha256);expect(zip.answer.state).toBe(a.state);expect(zip.evidence.sources).toEqual(a.request.payload.sources);for(const secret of [root,'SYNTHETIC_SELECTED_TEST_KEY','private_binding_json','private_native_session_id','UNSELECTED NOTE'])expect(JSON.stringify(zip)).not.toContain(secret);receipt('zip-'+label,{target,sha256:hash(fs.readFileSync(target)),...zip});return zip;};
 try{
  await launch();await req('/api/settings/ai','PUT',{settings:{ai_cli_path:fake.cli,assistant_runtime:mode==='question'?'claude_cli':'api_key',assistant_provider:'custom',assistant_model:'requested-synthetic-model',ai_custom_base_url:fake.base}});
  await win.evaluate(()=>{location.hash='/library';});await win.getByRole('button',{name:'Choose parent folder',exact:true}).click();await win.getByRole('button',{name:'Create managed vault',exact:true}).click();await win.getByLabel('Import PDF, TXT or MD').setInputFiles(names.map(n=>path.join(originals,n)));await expect(win.getByText(/3 retained, 0 exact duplicates/)).toBeVisible();const status=await req<LibraryStatus>('/api/library');vid=status.vault!.vault_id;vaultRoot=path.join(parent,status.vault!.label);catalog=(await req<LibraryPage>(`/api/library/files?expected_vault_id=${vid}`)).files;
  await win.getByRole('region',{name:'Library files'}).getByRole('button',{name:/^two-pages.pdf /}).click();await win.getByRole('link',{name:'Open in Evidence / add to project'}).click();await win.getByLabel('New project name',{exact:true}).fill('Synthetic selected '+mode);await win.getByRole('button',{name:'Create project',exact:true}).click();await win.getByRole('button',{name:'Add selected Library file to project'}).click();await expect(win.getByLabel('Canonical page text')).toHaveValue('Alpha evidence — exact version.');pid=(await req<{projects:Project[]}>(`/api/evidence/projects?expected_vault_id=${vid}`)).projects[0].project_id;
  await expect(win.getByRole('region',{name:'PDF page image'})).toContainText('Page 1 of 2 rendered');const canvas=await win.locator('canvas[data-pdf-version]').evaluate(el=>{const c=el as HTMLCanvasElement,d=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data;let dark=0;for(let i=0;i<d.length;i+=4)if(d[i]<150&&d[i+1]<150&&d[i+2]<150&&d[i+3])dark++;return {width:c.width,height:c.height,dark};});expect(canvas.dark).toBeGreaterThan(10);receipt('pdf-canvas',canvas);
  await win.getByLabel('Note body',{exact:true}).fill('SELECTED OWNER NOTE <script>literal</script>');await win.getByRole('button',{name:'Save note',exact:true}).click();await expect(win.getByText('SELECTED OWNER NOTE <script>literal</script>',{exact:true}).first()).toBeVisible();await win.getByRole('button',{name:'Choose from Library'}).click();for(const name of ['unicode.txt','hostile.md']){await win.getByRole('button',{name:'Add '+name,exact:true}).click();await expect(win.getByRole('button',{name:'Choose from Library'})).toBeEnabled();}await win.getByRole('button',{name:'Close Library chooser'}).click();
  await win.getByRole('region',{name:'Current collection files'}).getByRole('button',{name:/^unicode.txt /}).click();const canonical=fs.readFileSync(path.join(originals,'unicode.txt'),'utf8').replace(/\r\n|\r/g,'\n');await expect(win.getByLabel('Canonical page text')).toHaveValue(canonical);await win.getByLabel('Find on current canonical page').fill('repeat needle');await win.getByRole('button',{name:'Find next literal match'}).click();await win.getByRole('button',{name:'Find next literal match'}).click();await win.getByRole('button',{name:'Use selected passage'}).click();
  const none=await prepare();expect(fake.captures()).toHaveLength(0);expect(fake.requests).toHaveLength(0);expect((await answers()).total).toBe(0);expect(none.preview.request.payload.notes).toEqual([]);expect(none.preview.request.payload.sources).toHaveLength(2);expect(none.preview.request.payload.coverage.files.find(f=>f.known_page_count===2)?.unexamined_page_count).toBe(1);expect(none.preview.request.user_prompt).not.toContain('SELECTED OWNER NOTE');expect(none.preview.request.user_prompt).not.toContain('hostile.md');await screenshot('preview-no-send');
  await app!.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(2));const close=none.dialog.getByRole('button',{name:'Close preview without sending'});await close.focus();await win.keyboard.press('Tab');await expect(none.dialog.getByRole('button',{name:'Close selection'})).toBeFocused();await win.keyboard.press('Shift+Tab');await expect(close).toBeFocused();const geometry=await none.dialog.evaluate(el=>({left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right,width:innerWidth,scroll:el.scrollWidth,client:el.clientWidth}));expect(geometry.left).toBeGreaterThanOrEqual(0);expect(geometry.right).toBeLessThanOrEqual(geometry.width);expect(geometry.scroll).toBeLessThanOrEqual(geometry.client);receipt('zoom200-keyboard',geometry);await screenshot('zoom200-preview');await win.keyboard.press('Enter');await expect(none.dialog.getByRole('heading',{name:'Inspect before Send'})).toHaveCount(0);await win.keyboard.press('Escape');await expect(win.getByRole('button',{name:'New selected-evidence answer'})).toBeFocused();await app!.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(1));
  for(const outcome of ['success','error'] as const){
   await holdResponse(base+`/api/evidence/projects/${pid}/answer-previews`,outcome==='error');await win.getByRole('button',{name:'New selected-evidence answer'}).click();const dialog=win.getByRole('dialog',{name:'Select evidence for an answer'});await dialog.getByRole('button',{name:'Add unicode.txt logical page 1'}).click();await dialog.getByLabel('Question or briefing instruction').fill('Retired preview '+outcome);await dialog.getByRole('button',{name:'Preview selected content'}).click();await expect.poll(async()=>(await heldResponse()).ready).toBe(true);const held=await heldResponse();expect(held.status).toBe(200);await dialog.getByRole('button',{name:'Close selection'}).click();await releaseResponse();
   await expect(win.getByRole('dialog',{name:'Select evidence for an answer'})).toHaveCount(0);expect(await win.getByText('RETIRED_PREVIEW_ERROR').count()).toBe(0);expect(fake.captures().length+fake.requests.length).toBe(0);receipt('held-preview-'+outcome,{actualUpstreamStatus:held.status,retiredBeforeDelivery:true,injectedTransportError:outcome==='error',invocations:0});
  }
  const complete=await send('succeeded',true);expect((await answers()).total).toBe(1);expect(JSON.parse(sql()).assistant_sessions).toBe(0);expect(complete.request.payload.notes).toHaveLength(1);await expect(win.getByRole('article',{name:'Selected evidence answer'})).toContainText('Owner-note summary');expect(complete.reports[0].model).toBe(mode==='question'?'reported-synthetic-cli':'reported-synthetic-api');expect(complete.request.payload.requested.requested_model).toBe('requested-synthetic-model');expect(complete.usage).toEqual({reported:{input_tokens:0,output_tokens:12},provenance:'runtime_report',billing:'unknown'});
  if(mode==='question'){expect(fake.captures()).toHaveLength(1);const c=fake.captures()[0];expect(c.prompt).toBe(complete.request.user_prompt);expect(c.argv[c.argv.indexOf('--append-system-prompt')+1]).toBe(complete.request.system_text);expect(c.config).toEqual({mcpServers:{}});expect(c.argv).not.toContain('--resume');expect(fs.existsSync(c.cwd)).toBe(false);}else{expect(fake.requests).toHaveLength(1);const capture=fake.requests[0] as {body:{messages:unknown[];tools?:unknown}};expect(capture.body.messages).toEqual([{role:'system',content:complete.request.system_text},{role:'user',content:complete.request.user_prompt}]);expect(capture.body.tools).toBeUndefined();}
  expect(await win.locator('.selected-answer script,.selected-answer img,.selected-answer a').count()).toBe(0);await win.getByRole('button',{name:/Open citation S01/}).click();await expect(win.getByRole('region',{name:'Saved citation excerpt'})).toContainText(complete.result!.sections[0].items[0].citations[0].quote);await expect(win.getByText('Citation matched this exact current text range. Semantic support remains unchecked.',{exact:true})).toBeVisible();expect(await win.getByRole('region',{name:'Saved citation excerpt'}).getByLabel('Canonical page text').evaluate(el=>{const t=el as HTMLTextAreaElement;return t.value.slice(t.selectionStart,t.selectionEnd);})).toBe(complete.result!.sections[0].items[0].citations[0].quote);await screenshot('complete-citation');await exportAnswer(complete,'complete');
  // Strict invalid and unsupported output never becomes a complete answer.
  for(const fault of mode==='question'?['invalid','unsupported','missing_done','insufficient']:['invalid','missing_done']){fake.setFault(fault);const a=await send(fault==='insufficient'?'refused':'failed');expect(a.result===null).toBe(fault!=='insufficient');await expect(win.getByRole('article',{name:'Selected evidence answer'})).toContainText(fault==='insufficient'?'Insufficient selected text':'Incomplete / unvalidated output');}
  fake.setFault('partial_wait');const pending=await prepare();const start=await captureStart();await pending.dialog.getByRole('button',{name:'Send selected evidence'}).click();const active=JSON.parse((await capturedResponse(start,'/answers')).body) as Answer;if(mode==='question')await expect(win.getByRole('region',{name:'Unvalidated answer text'})).toContainText('UNVALIDATED partial');await win.getByRole('button',{name:'Stop selected answer'}).focus();await win.keyboard.press('Enter');await expect.poll(async()=>(await detail(active.answer_id)).state).toBe('cancelled');await expect.poll(async()=>(await detail(active.answer_id)).cleanup_state).toBe('confirmed');await expect(win.getByRole('button',{name:'New selected-evidence answer'})).toBeEnabled();const cancelled=await detail(active.answer_id);saved.push(cancelled);receipt('stop',cancelled);expect(cancelled.result).toBeNull();if(mode==='question'){expect(cancelled.partial_text).toContain('UNVALIDATED partial');const zip=await exportAnswer(cancelled,'partial');expect(zip.markdown).toContain('Incomplete / unvalidated');}await screenshot('cancelled');
  // A Send already admitted by real HTTP can arrive after the dialog retires.
  // The late response must cancel that exact job and never replace the view.
  fake.setFault('partial_wait');const late=await prepare();await holdResponse(base+`/api/evidence/projects/${pid}/answers`);
  await late.dialog.getByRole('button',{name:'Send selected evidence'}).click();await expect.poll(async()=>(await heldResponse()).ready).toBe(true);const heldSend=await heldResponse();expect(heldSend.status).toBe(202);const lateAnswer=JSON.parse(heldSend.body) as Answer;await late.dialog.getByRole('button',{name:'Close selection'}).click();await releaseResponse();await expect.poll(async()=>(await detail(lateAnswer.answer_id)).state).toBe('cancelled');await expect.poll(async()=>(await detail(lateAnswer.answer_id)).cleanup_state).toBe('confirmed');expect(await win.getByRole('article',{name:'Selected evidence answer'}).textContent()).toContain(cancelled.answer_id);const retired=await detail(lateAnswer.answer_id);saved.push(retired);receipt('retired-send',retired);
  // Graceful actual main/backend restart, then saved reads with original files unavailable.
  const beforeRestart=py("import sqlite3,json,sys;c=sqlite3.connect(sys.argv[1]);print(json.dumps(list(c.execute('SELECT * FROM evidence_answers ORDER BY id'))));c.close()",env.RESMON_DB_PATH);const callsBefore=fake.captures().length+fake.requests.length;const mainPid=app!.process().pid!;await app!.close();await expect.poll(()=>alive(mainPid)).toBe(false);await expect.poll(()=>backends.filter(alive)).toEqual([]);await launch();await win.evaluate(projectId=>{location.hash='/evidence?project_id='+projectId;},pid);await win.waitForSelector('.evidence-page');
  const retained=catalog.map(f=>path.join(vaultRoot,f.relative_path));for(const target of retained)fs.renameSync(target,target+'.held');try{await win.getByRole('region',{name:'Saved answer history'}).getByRole('button').filter({hasText:complete.answer_id}).click();await expect(win.getByRole('article',{name:'Selected evidence answer'})).toContainText(complete.answer_id);await exportAnswer(complete,'restart-missing-originals');expect(fake.captures().length+fake.requests.length).toBe(callsBefore);await win.getByRole('button',{name:/Open citation S01/}).click();await expect(win.getByRole('region',{name:'Saved citation excerpt'}).getByRole('alert').first()).toBeVisible();await expect(win.getByRole('region',{name:'Saved citation excerpt'}).getByLabel('Canonical page text')).toHaveCount(0);await screenshot('saved-missing-original');}finally{for(const target of retained)fs.renameSync(target+'.held',target);}
  expect(py("import sqlite3,json,sys;c=sqlite3.connect(sys.argv[1]);print(json.dumps(list(c.execute('SELECT * FROM evidence_answers ORDER BY id'))));c.close()",env.RESMON_DB_PATH)).toBe(beforeRestart);
  // Seed 51 additional terminal snapshots solely to challenge pagination; these
  // are labelled fixture rows, never represented as additional Sends/model work.
  const seed=JSON.parse(py("import sqlite3,sys,uuid,json;c=sqlite3.connect(sys.argv[1]);c.row_factory=sqlite3.Row;r=dict(c.execute('SELECT * FROM evidence_answers WHERE answer_id=?',(sys.argv[2],)).fetchone());r.pop('id');ids=[]\nfor _ in range(51):\n r['answer_id']=str(uuid.uuid4());r['preview_id']=str(uuid.uuid4());ids.append(r['answer_id']);c.execute('INSERT INTO evidence_answers ('+','.join(r)+') VALUES ('+','.join('?' for _ in r)+')',tuple(r.values()))\nc.commit();c.close();print(json.dumps(ids))",env.RESMON_DB_PATH,complete.answer_id)) as string[];receipt('synthetic-history-seed',{count:51,ids:seed,basis:'Exact prior terminal snapshot with unique answer/preview identities; zero Send or model requests'});await win.getByRole('button',{name:'Refresh answers'}).click();await expect(win.getByText(new RegExp('50 shown of '+(saved.length+51)+' saved answers'))).toBeVisible();await win.getByRole('button',{name:'Next saved answers'}).click();await expect(win.getByRole('region',{name:'Saved answer history'})).toContainText(seed[50]);await win.getByRole('region',{name:'Saved answer history'}).getByRole('button').filter({hasText:seed[50]}).click();await expect(win.getByRole('article',{name:'Selected evidence answer'})).toContainText(seed[50]);expect(fake.captures().length+fake.requests.length).toBe(callsBefore);await screenshot('history-page-two');
  if(mode==='question'){
   fake.setFault('crash_wait');const p=await prepare();const start=await captureStart();await p.dialog.getByRole('button',{name:'Send selected evidence'}).click();const active=JSON.parse((await capturedResponse(start,'/answers')).body) as Answer;
   await expect.poll(async()=>(await detail(active.answer_id)).partial_text).toContain('durable checkpoint');const checkpoint=await detail(active.answer_id),backendPid=backends[backends.length-1],backendStart=started(backendPid),child=fake.captures()[fake.captures().length-1];expect(checkpoint.state).toBe('running');expect(child).toBeTruthy();const childStart=started(child.pid);const beforeCrashCalls=fake.captures().length;
   process.kill(backendPid,'SIGKILL');await expect.poll(()=>alive(backendPid)).toBe(false);if(alive(child.pid)){expect(started(child.pid)).toBe(childStart);process.kill(child.pid,'SIGKILL');}await expect.poll(()=>alive(child.pid)).toBe(false);await app!.close();await launch();await win.evaluate(projectId=>{location.hash='/evidence?project_id='+projectId;},pid);await win.waitForSelector('.evidence-page');
   const interrupted=await detail(active.answer_id);expect(interrupted.state).toBe('interrupted');expect(interrupted.cleanup_state).toBe('unknown');expect(interrupted.partial_text).toBe(checkpoint.partial_text);expect(interrupted.result).toBeNull();expect(fake.captures()).toHaveLength(beforeCrashCalls);
   // It is beyond page one after the explicit synthetic pagination seed.
   await win.getByRole('button',{name:'Next saved answers'}).click();await win.getByRole('region',{name:'Saved answer history'}).getByRole('button').filter({hasText:active.answer_id}).click();await expect(win.getByRole('article',{name:'Selected evidence answer'})).toContainText('interrupted');await exportAnswer(interrupted,'interrupted-restart');receipt('abrupt-restart',{backendPid,backendStart,childPid:child.pid,childStart,checkpoint,interrupted,priorCalls:beforeCrashCalls,afterCalls:fake.captures().length,cleanup:'Only the identified test backend and its captured fake child were killed; prior cleanup remains unknown in the app'});
  }
  for(const theme of ['light','dark'] as const){await app!.evaluate(({nativeTheme},value)=>{nativeTheme.themeSource=value;},theme);await screenshot(theme);}
  for(const name of names)expect(hash(fs.readFileSync(path.join(originals,name)))).toBe(originalHashes[name]);const net=await app!.evaluate(()=>(globalThis as unknown as {selectedNetwork:{allowed:string[];blocked:string[];opens:string[]}}).selectedNetwork);expect(net.blocked).toEqual([]);expect(net.opens).toEqual([]);receipt('network',net);receipt('preservation',{originalHashes,current:Object.fromEntries(names.map(n=>[n,hash(fs.readFileSync(path.join(originals,n)))])),sql:JSON.parse(sql()),state,profile,vaultRoot});expect(errors).toEqual([]);
 }finally{
  receipt('cli-captures',fake.captures());receipt('api-captures',fake.requests);if(win&&!win.isClosed()){await screenshot('terminal').catch(()=>{});receipt('terminal',{body:await win.locator('body').innerText().catch(()=>''),errors});}
  if(app){receipt('network-at-cleanup',await app.evaluate(()=>(globalThis as unknown as {selectedNetwork:unknown}).selectedNetwork).catch(()=>null));const owned=app.process().pid!;await app.close().catch(()=>{});await expect.poll(()=>alive(owned)).toBe(false);}await fake.close();await expect.poll(()=>backends.filter(alive)).toEqual([]);receipt('cleanup',{root,instances,backends,remaining:backends.filter(alive),captureProcesses:fake.captures().map(c=>({pid:c.pid,alive:alive(c.pid)})),preservedSyntheticState:true,at:new Date().toISOString()});
 }
});
