# resmon_scripts/verification_scripts/test_api_contract.py
"""The HTTP surface against the committed contract.

``docs/api-contract/openapi.json`` and ``docs/api-contract/http.md`` describe
every route the renderer, the MCP server and the assistant use. They are
generated by ``implementation_scripts/api_contract.py`` from the real FastAPI
application, and this file regenerates them in-process and fails on any
difference.

**A contract change takes its own pull request.** That is what these tests are
for. When one of them goes red the answer is never to edit the committed file
by hand: run

    python -m implementation_scripts.api_contract --write

from ``resmon_scripts/``, look at the diff, and if the surface really did
change, open a pull request whose body says which routes changed and why. The
renderer is rebuilt against this file; a screen may call what is in it and
nothing else, so a silent change here is a change nobody downstream can see
coming.

The failures below are deliberately per-route. One assertion over a 130 KB
document tells you that something moved and leaves you to find it; naming the
routes that were added, removed or reshaped is the difference between a red
test you can act on and one you re-run hoping.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "resmon_scripts"))

from implementation_scripts import api_contract  # noqa: E402


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

#: The methods an operation may appear under in an OpenAPI path item.
_METHODS = ("get", "put", "post", "delete", "options", "head", "patch", "trace")

#: The parts of an operation that are prose rather than shape. A change to one
#: of these is still a change to the committed file — the guard goes red either
#: way — but the failure says which kind it is, because "somebody improved a
#: docstring" and "the request body lost a field" want different reviewers.
_PROSE_KEYS = frozenset({"description", "summary"})


def _operations(document: dict) -> dict[tuple[str, str], dict]:
    """``(METHOD, path)`` -> operation, for every operation in the document."""
    out: dict[tuple[str, str], dict] = {}
    for path, item in (document.get("paths") or {}).items():
        for method in _METHODS:
            if method in item:
                out[(method.upper(), path)] = item[method]
    return out


def _shape(operation: dict) -> dict:
    """The operation with its prose taken out."""
    return {k: v for k, v in operation.items() if k not in _PROSE_KEYS}


def _committed(path: Path) -> str:
    if not path.exists():  # pragma: no cover — only on a broken checkout
        pytest.fail(
            f"{path.relative_to(PROJECT_ROOT)} is missing. Generate it with "
            f"`{api_contract.REGENERATE_COMMAND}` from resmon_scripts/."
        )
    return path.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def fresh_openapi() -> dict:
    return api_contract.normalised_openapi()


@pytest.fixture(scope="module")
def committed_openapi() -> dict:
    return json.loads(_committed(api_contract.OPENAPI_PATH))


# ---------------------------------------------------------------------------
# The document itself
# ---------------------------------------------------------------------------

def test_committed_openapi_describes_the_routes_the_app_has(
    fresh_openapi, committed_openapi
):
    """Every route in the app is in the contract, and nothing else is.

    The first of the per-route checks and the one that catches a route added or
    deleted. It runs before the shape comparison on purpose: a route that is
    simply absent explains every downstream difference, and reporting both at
    once buries it.
    """
    fresh = set(_operations(fresh_openapi))
    committed = set(_operations(committed_openapi))
    added = sorted(f"{m} {p}" for m, p in fresh - committed)
    removed = sorted(f"{m} {p}" for m, p in committed - fresh)
    assert not (added or removed), (
        "The app's routes and docs/api-contract/openapi.json disagree.\n"
        + ("".join(f"  added, not in the contract: {r}\n" for r in added))
        + ("".join(f"  in the contract, no longer a route: {r}\n" for r in removed))
        + f"A contract change takes its own PR. Regenerate with "
          f"`{api_contract.REGENERATE_COMMAND}` and say in the PR body what changed."
    )


def test_every_route_keeps_the_shape_the_contract_gives_it(
    fresh_openapi, committed_openapi
):
    """Parameters, request bodies and responses, one route at a time."""
    fresh = _operations(fresh_openapi)
    committed = _operations(committed_openapi)
    differences = []
    for key in sorted(fresh.keys() & committed.keys()):
        if _shape(fresh[key]) != _shape(committed[key]):
            differences.append(f"  {key[0]} {key[1]}: request or response shape")
        elif fresh[key] != committed[key]:
            differences.append(f"  {key[0]} {key[1]}: summary or description only")
    assert not differences, (
        "Routes whose description in docs/api-contract/openapi.json is out of date:\n"
        + "\n".join(differences)
        + f"\nRegenerate with `{api_contract.REGENERATE_COMMAND}`. A line reading "
          "'summary or description only' is a docstring edit and not a change to the "
          "seam; anything else is, and the PR body says what moved and why."
    )


def test_the_shared_schemas_match(fresh_openapi, committed_openapi):
    """``components.schemas`` — the request models — one model at a time."""
    fresh = (fresh_openapi.get("components") or {}).get("schemas") or {}
    committed = (committed_openapi.get("components") or {}).get("schemas") or {}
    added = sorted(set(fresh) - set(committed))
    removed = sorted(set(committed) - set(fresh))
    changed = sorted(
        name for name in set(fresh) & set(committed) if fresh[name] != committed[name]
    )
    assert not (added or removed or changed), (
        "docs/api-contract/openapi.json disagrees with the app's models.\n"
        + "".join(f"  new model: {n}\n" for n in added)
        + "".join(f"  model gone: {n}\n" for n in removed)
        + "".join(f"  model changed: {n}\n" for n in changed)
        + f"Regenerate with `{api_contract.REGENERATE_COMMAND}`."
    )


def test_committed_openapi_is_byte_for_byte_a_fresh_generation():
    """The last word, after the readable per-route failures above.

    Those name what changed; this one is what makes the file *the* contract
    rather than an approximation of it — whitespace, key order and the trailing
    newline included.
    """
    assert _committed(api_contract.OPENAPI_PATH) == api_contract.contract_json(), (
        "docs/api-contract/openapi.json is not what the app generates. "
        f"Regenerate with `{api_contract.REGENERATE_COMMAND}`."
    )


def test_the_contract_carries_no_app_version(committed_openapi):
    """``info.version`` is removed, so a release does not move the contract."""
    assert "version" not in (committed_openapi.get("info") or {}), (
        "info.version is back in the contract. It is the app version, it moves at "
        "every release, and a contract that changes then says nothing about whether "
        "the surface changed."
    )


def test_no_route_declares_a_response_model():
    """0 of 184 — and the index says so rather than inventing schemas.

    This is not a rule about how routes should be written; it is the fact the
    index is honest about. If a route ever does declare one, this test is the
    prompt to say so in ``http.md`` instead of leaving the reader with a claim
    that has quietly stopped being true.
    """
    routes = api_contract.api_routes()
    declared = sorted(
        f"{sorted(r.methods)[0]} {r.path}" for r in routes if r.response_model is not None
    )
    assert not declared, (
        "These routes now declare a response_model, so docs/api-contract/http.md's "
        "'not one of the routes declares a response_model' is no longer true:\n  "
        + "\n  ".join(declared)
    )


# ---------------------------------------------------------------------------
# The route count
# ---------------------------------------------------------------------------

def test_the_route_count_is_what_the_docs_say():
    """``app.routes`` against the number written down in three places.

    ``AGENTS.md`` has said "184 routes" since the file was written, and the
    index and the generator's own docstring repeat it. A count in prose is a
    claim, and a claim with nothing checking it drifts: this is what stops the
    number being right about a version of the app that no longer exists.
    """
    actual = len(api_contract.route_keys())
    assert actual == len(api_contract.api_routes()), (
        "A route declares more than one method, so the (method, path) count and the "
        "route count have come apart. The docs state one number for both."
    )

    stated = {
        "docs/api-contract/http.md": _committed(api_contract.HTTP_INDEX_PATH),
        "AGENTS.md": (PROJECT_ROOT / "AGENTS.md").read_text(encoding="utf-8"),
    }
    for name, text in stated.items():
        assert f"{actual} routes" in text, (
            f"{name} does not say '{actual} routes'. The app has {actual}."
        )


# ---------------------------------------------------------------------------
# The index
# ---------------------------------------------------------------------------

def test_committed_index_is_a_fresh_generation():
    """``http.md`` byte for byte, including the tables and the counts."""
    assert _committed(api_contract.HTTP_INDEX_PATH) == api_contract.render_http_md(), (
        "docs/api-contract/http.md is not what the generator produces. Regenerate "
        f"with `{api_contract.REGENERATE_COMMAND}` — never edit it by hand."
    )


def test_every_route_is_mapped_to_a_register_row():
    """184 of 184. A new route is red until somebody says what it serves.

    The point of the index is that a renderer rebuild can ask "which screens
    does this route belong to" and get an answer for every route. One route
    with no answer makes that false for the whole file, so an unmapped route
    fails here rather than quietly rendering as absent.
    """
    unmapped = [
        f"{method} {path}"
        for method, path in api_contract.route_keys()
        if (method, path) not in api_contract.ROUTE_JOURNEYS
    ]
    assert not unmapped, (
        "Routes with no row in api_contract.ROUTE_JOURNEYS:\n  "
        + "\n  ".join(sorted(unmapped))
        + "\nAdd each one to the mapping with the register row (J01…J44) it serves."
    )


def test_the_mapping_has_no_route_the_app_does_not():
    """The other direction: a mapping entry for a route that has gone."""
    actual = set(api_contract.route_keys())
    stale = [f"{m} {p}" for m, p in api_contract.ROUTE_JOURNEYS if (m, p) not in actual]
    assert not stale, (
        "api_contract.ROUTE_JOURNEYS maps routes the app no longer has:\n  "
        + "\n  ".join(sorted(stale))
    )


def test_every_register_id_used_is_one_of_the_forty_four():
    """``J45`` and ``J7`` are both typos, and both would render as a lost row."""
    assert len(api_contract.REGISTER) == 44
    known = set(api_contract.REGISTER_TITLES)
    used = {
        journey
        for journeys in api_contract.ROUTE_JOURNEYS.values()
        for journey in journeys
    }
    assert used <= known, (
        "Register ids used by the mapping that are not in the register: "
        + ", ".join(sorted(used - known))
    )
    assert set(api_contract.ROWLESS_REASONS) <= known


def test_every_register_row_appears_in_the_index():
    """All 44 headings, in order, whether or not they carry a route."""
    index = _committed(api_contract.HTTP_INDEX_PATH)
    position = -1
    for jid, title in api_contract.REGISTER:
        heading = f"## {jid} — {title}"
        found = index.find(heading)
        assert found > -1, f"{heading!r} is not in docs/api-contract/http.md"
        assert found > position, f"{jid} is out of order in docs/api-contract/http.md"
        position = found


def test_a_row_with_no_route_says_so():
    """An empty table and an unwritten one look identical; neither is allowed."""
    rows_with_routes = {
        journey
        for journeys in api_contract.ROUTE_JOURNEYS.values()
        for journey in journeys
    }
    mcp_keys, _ = api_contract.mcp_driven_routes()
    if mcp_keys:
        rows_with_routes.add("J44")
    rowless = {jid for jid, _ in api_contract.REGISTER} - rows_with_routes
    assert rowless == set(api_contract.ROWLESS_REASONS), (
        "The rows with no route and the rows with a written reason have come apart. "
        f"No route: {sorted(rowless)}; reason written: "
        f"{sorted(api_contract.ROWLESS_REASONS)}."
    )


# ---------------------------------------------------------------------------
# Vocabularies
# ---------------------------------------------------------------------------

def test_each_vocabulary_in_the_index_equals_its_constant():
    """The words in ``http.md`` against the objects they were read from.

    Generated and then checked, rather than generated and trusted: a value
    typed into the document by hand fails here, and so does a value added to
    the constant and not regenerated.
    """
    index = _committed(api_contract.HTTP_INDEX_PATH)
    for heading, origin, values in api_contract.vocabularies():
        line = f"**{heading}** — from {origin}. {len(values)} values:"
        assert line in index, (
            f"docs/api-contract/http.md does not carry {heading!r} as "
            f"{len(values)} values from {origin}."
        )
        rendered = "".join(f"`{value}` · " for value in values).rstrip(" ·")
        start = index.index(line)
        assert rendered in index[start:start + len(line) + len(rendered) + 8], (
            f"The {heading!r} values in docs/api-contract/http.md are not "
            f"{list(values)}."
        )


def test_the_execution_status_vocabulary_is_the_schemas():
    """Guards the parse itself, the way the renderer's vocabulary test does.

    A reformat of ``_EXECUTIONS_V19_DDL`` that made the regex miss would
    otherwise yield an empty tuple, and an empty tuple compares equal to an
    empty rendering: the document would go on saying nothing, truthfully, for
    ever.
    """
    statuses = api_contract._execution_statuses()
    assert "running" in statuses and "interrupted" in statuses
    assert len(statuses) >= 5


def test_the_guard_refusals_are_read_out_of_the_guard():
    """The four the guard can answer with — and not the route's fifth.

    ``403 signature_invalid`` belongs to ``GET /api/deliveries/{id}/bundle``,
    which checks a per-destination HMAC rather than the token. It is not a
    guard refusal and must not appear in the guard's list.
    """
    refusals = dict((reason, status) for status, reason in api_contract._guard_refusals())
    assert refusals == {
        "token_missing": 401,
        "token_invalid": 401,
        "host_refused": 403,
        "origin_refused": 403,
    }


def test_the_auth_class_comes_from_the_guards_own_constants():
    """One signed route, no exempt routes, everything else on the token."""
    from implementation_scripts import api_auth

    assert api_auth.AUTH_EXEMPT_PATHS == frozenset(), (
        "AUTH_EXEMPT_PATHS has grown. docs/api-contract/http.md says it is empty."
    )
    classes: dict[str, list[str]] = {}
    for _method, path in api_contract.route_keys():
        classes.setdefault(api_contract.auth_class(path), []).append(path)
    assert sorted(set(classes.get("signed link", []))) == [
        "/api/deliveries/{delivery_id}/bundle"
    ]
    assert "exempt" not in classes
    assert len(set(classes["token"])) == len(
        {path for _m, path in api_contract.route_keys()}
    ) - 1


# ---------------------------------------------------------------------------
# Determinism
# ---------------------------------------------------------------------------

def test_two_generations_are_byte_identical():
    """The same process, twice. Sorted keys are what make this true.

    CI runs this file on Python 3.10, 3.11 and 3.12, which is the part of P4
    this cannot reach from one interpreter: three versions agreeing on the
    committed bytes is three green columns, not an assertion here.
    """
    assert api_contract.contract_json() == api_contract.contract_json()
    assert api_contract.render_http_md() == api_contract.render_http_md()


def test_sse_routes_are_the_three_that_stream():
    """Named, because "does this stream" is the question a client gets wrong.

    A client that fetches one of these and waits for a JSON body waits for
    ever. There is no declared response type to read, so the generator looks
    for the media type in the handler's own source; this pins what it found, so
    a fourth streaming route arrives as a red test rather than as a hang.
    """
    streaming = sorted(
        f"{sorted(route.methods)[0]} {route.path}"
        for route in api_contract.api_routes()
        if api_contract.streams_sse(route)
    )
    assert streaming == [
        "GET /api/evidence/projects/{project_id}/answers/{answer_id}/events",
        "GET /api/executions/{exec_id}/progress/stream",
        "POST /api/assistant/sessions/{session_id}/messages",
    ]
